#pragma once

#define MESSAGE_RECEIVED_LAUNCH_SERVICES_DATABASE "Received Launch Services database"
#define MESSAGE_WAITING_FOR_LAUNCH_SERVICES_DATABASE_UPDATE_TOOK_F_SECONDS "Waiting for Launch Services database update took %f seconds"
#define MESSAGE_TIMED_OUT_WAITING_FOR_LAUNCH_SERVICES_DATABASE_UPDATE "Timed out waiting for Launch Services database update"
#define MESSAGE_PLATFORM_INITIALIZE_WEBPROCESS "WebProcess::platformInitializeWebProcess"
#define MESSAGE_WEBRESOURCELOADER_CONSTRUCTOR "[webPageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 "] WebResourceLoader::WebResourceLoader"
#define MESSAGE_WEBRESOURCELOADER_WILLSENDREQUEST "[webPageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 "] WebResourceLoader::willSendRequest"
#define MESSAGE_WEBRESOURCELOADER_WILLSENDREQUEST_NO_CORELOADER "[webPageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 "] WebResourceLoader::willSendRequest: exiting early because no coreloader or identifier"
#define MESSAGE_WEBRESOURCELOADER_WILLSENDREQUEST_CONTINUE "[webPageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 "] WebResourceLoader::willSendRequest: returning ContinueWillSendRequest"
#define MESSAGE_WEBRESOURCELOADER_DIDRECEIVERESPONSE "[webPageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 "] WebResourceLoader::didReceiveResponse: (httpStatusCode=%d)"
#define MESSAGE_WEBRESOURCELOADER_DIDRECEIVERESPONSE_NOT_CONTINUING_LOAD "[webPageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 "] WebResourceLoader::didReceiveResponse: not continuing load because no coreLoader or no ID"
#define MESSAGE_WEBRESOURCELOADER_DIDRECEIVERESPONSE_NOT_CONTINUING_INTERCEPT_LOAD "[webPageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 "] WebResourceLoader::didReceiveResponse: not continuing intercept load because no coreLoader or no ID"
#define MESSAGE_WEBRESOURCELOADER_DIDRECEIVEDATA "[webPageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 "] WebResourceLoader::didReceiveData: Started receiving data"
#define MESSAGE_WEBRESOURCELOADER_DIDFINISHRESOURCELOAD "[webPageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 "] WebResourceLoader::didFinishResourceLoad: (length=%llu)"
#define MESSAGE_WEBRESOURCELOADER_SERVICEWORKERDIDNOTHANDLE "[webPageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 "] WebResourceLoader::serviceWorkerDidNotHandle"
#define MESSAGE_WEBRESOURCELOADER_DIDFAILRESOURCELOAD "[webPageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 "] WebResourceLoader::didFailResourceLoad"
#define MESSAGE_WEBRESOURCELOADER_DIDBLOCKAUTHENTICATIONCHALLENGE "[webPageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 "] WebResourceLoader::didBlockAuthenticationChallenge"
#define MESSAGE_WEBRESOURCELOADER_STOPLOADINGAFTERSECURITYPOLICYDENIED "[webPageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 "] WebResourceLoader::stopLoadingAfterXFrameOptionsOrContentSecurityPolicyDenied"
#define MESSAGE_WEBRESOURCELOADER_DIDRECEIVERESOURCE "[webPageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 "] WebResourceLoader::didReceiveResource"
#define MESSAGE_WEBRESOURCELOADER_DIDRECEIVERESOURCE_UNABLE_TO_CREATE_FRAGMENTEDSHAREDBUFFER "[webPageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 "] WebResourceLoader::didReceiveResource: Unable to create FragmentedSharedBuffer"
#define MESSAGE_WEBLOADERSTRATEGY_SCHEDULELOAD "[webPageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 "] WebLoaderStrategy::scheduleLoad: URL will be scheduled with the NetworkProcess"
#define MESSAGE_WEBLOADERSTRATEGY_SCHEDULELOAD_URL_LOADED_AS_DATA "[webPageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 "] WebLoaderStrategy::scheduleLoad: URL will be loaded as data"
#define MESSAGE_WEBLOADERSTRATEGY_SCHEDULELOAD_RESOURCE_SCHEDULED_WITH_NETWORKPROCESS "[webPageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 "] WebLoaderStrategy::scheduleLoad: Resource is being scheduled with the NetworkProcess (priority=%d, existingNetworkResourceLoadIdentifierToResume=%" PRIu64 ")"
#define MESSAGE_WEBFRAMELOADERCLIENT_NAVIGATIONACTIONDATA_NO_WEBPAGE "[webFrameID=%" PRIu64 ", webPageID=%" PRIu64 "] WebFrameLoaderClient::navigationActionData: returning std::nullopt because there's no web page"
#define MESSAGE_WEBFRAMELOADERCLIENT_NAVIGATIONACTIONDATA_EMPTY_REQUEST "[webFrameID=%" PRIu64 ", webPageID=%" PRIu64 "] WebFrameLoaderClient::dispatchDecidePolicyForNavigationAction: returning std::nullopt because request is empty"
#define MESSAGE_WEBFRAMELOADERCLIENT_NAVIGATIONACTIONDATA_NO_FRAME "[webFrameID=%" PRIu64 ", webPageID=%" PRIu64 "] WebFrameLoaderClient::dispatchDecidePolicyForNavigationAction: returning std::nullopt because frame does not exist"
#define MESSAGE_WEBFRAMELOADERCLIENT_DISPATCHDECIDEPOLICYFORNAVIGATIONACTION_SYNC_IPC_FAILED "[webFrameID=%" PRIu64 ", webPageID=%" PRIu64 "] WebFrameLoaderClient::dispatchDecidePolicyForNavigationAction: ignoring because of failing to send sync IPC, error = %hhu"
#define MESSAGE_WEBFRAMELOADERCLIENT_DISPATCHDECIDEPOLICYFORNAVIGATIONACTION_GOT_POLICYACTION_FROM_SYNC_IPC "[webFrameID=%" PRIu64 ", webPageID=%" PRIu64 "] WebFrameLoaderClient::dispatchDecidePolicyForNavigationAction: Got policyAction %{public}s from sync IPC"
#define MESSAGE_WEBFRAMELOADERCLIENT_DISPATCHDECIDEPOLICYFORNAVIGATIONACTION_GOT_POLICYACTION_FROM_ASYNC_IPC "[webFrameID=%" PRIu64 ", webPageID=%" PRIu64 "] WebFrameLoaderClient::dispatchDecidePolicyForNavigationAction: Got policyAction %{public}s from async IPC"
#define MESSAGE_WEBPAGE_MARK_LAYERS_VOLATILE "[webPageID=%" PRIu64 "] WebPage::markLayersVolatile"
#define MESSAGE_WEBPAGE_FREEZE_LAYER_TREE "[webPageID=%" PRIu64 "] WebPage::freezeLayerTree: Adding a reason to freeze layer tree (reason=%d, new=%d, old=%d)"
#define MESSAGE_WEBPAGE_UNFREEZE_LAYER_TREE "[webPageID=%" PRIu64 "] WebPage::unfreezeLayerTree: Removing a reason to freeze layer tree (reason=%d, new=%d, old=%d)"
#define MESSAGE_WEBPAGE_FAILED_TO_MARK_ALL_LAYERS_VOLATILE "[webPageID=%" PRIu64 "] WebPage::markLayersVolatile: Failed to mark all layers as volatile, will retry in %g ms"
#define MESSAGE_WEBPAGE_LOADREQUEST "[webPageID=%" PRIu64 "] WebPage::loadRequest: navigationID=%" PRIu64 ", shouldTreatAsContinuingLoad=%u, lastNavigationWasAppInitiated=%d, existingNetworkResourceLoadIdentifierToResume=%" PRIu64
#define MESSAGE_WEBPAGE_CLOSE "[webPageID=%" PRIu64 "] WebPage::close"
#define MESSAGE_WEBPROCESS_PREPARE_TO_SUSPEND "[sessionID=%" PRIu64 "] WebProcess::prepareToSuspend: isSuspensionImminent=%d, remainingRunTime=%fs"
#define MESSAGE_WEBPROCESS_FREEZE_ALL_LAYER_TREES "[sessionID=%" PRIu64 "] WebProcess::freezeAllLayerTrees: WebProcess is freezing all layer trees"
#define MESSAGE_WEBPROCESS_DESTROY_RENDERING_RESOURCES "[sessionID=%" PRIu64 "] WebProcess::destroyRenderingResources: took %.2fms"
#define MESSAGE_WEBPROCESS_MARK_ALL_LAYERS_VOLATILE "[sessionID=%" PRIu64 "] WebProcess::markAllLayersVolatile:"
#define MESSAGE_WEBPROCESS_READY_TO_SUSPEND "[sessionID=%" PRIu64 "] WebProcess::prepareToSuspend: Process is ready to suspend"
#define MESSAGE_WEBLOCALFRAMELOADERCLIENT_COMPLETE_PAGE_TRANSITION_IF_NEEDED "[webFrameID=%" PRIu64 ", webPageID=%" PRIu64 "] WebLocalFrameLoaderClient::completePageTransitionIfNeeded: dispatching didCompletePageTransition"
#define MESSAGE_WEBLOCALFRAMELOADERCLIENT_DISPATCH_DID_FIRST_LAYOUT_FOR_FRAME "[webFrameID=%" PRIu64 ", webPageID=%" PRIu64 "] WebLocalFrameLoaderClient::dispatchDidReachLayoutMilestone: dispatching DidFirstLayoutForFrame"
#define MESSAGE_WEBLOCALFRAMELOADERCLIENT_DISPATCH_DID_REACH_LAYOUT_MILESTONE "[webFrameID=%" PRIu64 ", webPageID=%" PRIu64 "] WebLocalFrameLoaderClient::dispatchDidReachLayoutMilestone: dispatching DidReachLayoutMilestone (milestones=%{public}s)"
#define MESSAGE_WEBLOCALFRAMELOADERCLIENT_DISPATCH_DID_FIRST_VISUALLY_NONEMPTY_LAYOUT "[webFrameID=%" PRIu64 ", webPageID=%" PRIu64 "] WebLocalFrameLoaderClient::dispatchDidReachLayoutMilestone: dispatching DidFirstVisuallyNonEmptyLayoutForFrame"
#define MESSAGE_REMOTE_RENDERING_BACKEND_PROXY_CREATED_RENDERING_BACKEND "[renderingBackend=%" PRIu64 "] Created rendering backend for pageProxyID=%" PRIu64 ", webPageID=%" PRIu64
#define MESSAGE_VIDEOPRESENTATIONMANAGER_SETVIDEOLAYERFRAMEFENCED "VideoPresentationManager::setVideoLayerFrameFenced(%llu): send right %d, fence data size %llu"
#define MESSAGE_MEDIAPLAYERPRIVATEREMOTE_LAYERHOSTINGCONTEXTCHANGED "MediaPlayerPrivateRemote::layerHostingContextChanged"
