/*
 * THIS FILE WAS AUTOMATICALLY GENERATED, DO NOT EDIT.
 *
 * Copyright (C) 2020 Apple Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. AND ITS CONTRIBUTORS ``AS IS''
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL APPLE INC. OR ITS CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */

#pragma once

#define GENERATED_WEB_PREFERENCE_KEY_TYPE_MAPPINGS \
    { "DatabasesEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "LoadDeferringEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "AcceleratedCompositingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "AcceleratedCompositingForFixedPositionEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WirelessPlaybackTargetAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "LoadsImagesAutomatically", TestHeaderKeyType::BoolWebPreference }, \
    { "LinkPreconnect", TestHeaderKeyType::BoolWebPreference }, \
    { "LongRunningMediaCaptureStreamRepromptIntervalInHours", TestHeaderKeyType::DoubleWebPreference }, \
    { "WindowFocusRestricted", TestHeaderKeyType::BoolWebPreference }, \
    { "AggressiveTileRetentionEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "AllowContentSecurityPolicySourceStarToMatchAnyProtocol", TestHeaderKeyType::BoolWebPreference }, \
    { "AllowDisplayOfInsecureContent", TestHeaderKeyType::BoolWebPreference }, \
    { "AllowFileAccessFromFileURLs", TestHeaderKeyType::BoolWebPreference }, \
    { "LowPowerVideoAudioBufferSizeEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "AllowMultiElementImplicitSubmission", TestHeaderKeyType::BoolWebPreference }, \
    { "ManagedMediaSourceHighThreshold", TestHeaderKeyType::DoubleWebPreference }, \
    { "AllowRunningOfInsecureContent", TestHeaderKeyType::BoolWebPreference }, \
    { "AllowTestOnlyIPC", TestHeaderKeyType::BoolWebPreference }, \
    { "ManagedMediaSourceLowThreshold", TestHeaderKeyType::DoubleWebPreference }, \
    { "MathMLEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "MaxParseDuration", TestHeaderKeyType::DoubleWebPreference }, \
    { "MediaAudioCodecIDsAllowedInLockdownMode", TestHeaderKeyType::StringWebPreference }, \
    { "AllowsAirPlayForMediaPlayback", TestHeaderKeyType::BoolWebPreference }, \
    { "AllowsInlineMediaPlayback", TestHeaderKeyType::BoolWebPreference }, \
    { "AllowsInlineMediaPlaybackAfterFullscreen", TestHeaderKeyType::BoolWebPreference }, \
    { "AllowsPictureInPictureMediaPlayback", TestHeaderKeyType::BoolWebPreference }, \
    { "AlternateFullScreenControlDesignEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebSocketEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "MediaCapabilitiesEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebSecurityEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "AnimatedImageAsyncDecodingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "LayoutViewportHeightExpansionFactor", TestHeaderKeyType::DoubleWebPreference }, \
    { "LayoutFallbackWidth", TestHeaderKeyType::UInt32WebPreference }, \
    { "AppleMailPaginationQuirkEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ApplePayCapabilityDisclosureAllowed", TestHeaderKeyType::BoolWebPreference }, \
    { "ApplePayEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "LargeImageAsyncDecodingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "MediaCaptionFormatTypesAllowedInLockdownMode", TestHeaderKeyType::StringWebPreference }, \
    { "JavaScriptRuntimeFlags", TestHeaderKeyType::UInt32WebPreference }, \
    { "AsynchronousSpellCheckingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "JavaScriptMarkupEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "MediaCodecTypesAllowedInLockdownMode", TestHeaderKeyType::StringWebPreference }, \
    { "AudioControlsScaleWithPageZoom", TestHeaderKeyType::BoolWebPreference }, \
    { "JavaScriptCanOpenWindowsAutomatically", TestHeaderKeyType::BoolWebPreference }, \
    { "AuthorAndUserStylesEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebAudioEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "JavaScriptCanAccessClipboard", TestHeaderKeyType::BoolWebPreference }, \
    { "WantsBalancedSetDefersLoadingBehavior", TestHeaderKeyType::BoolWebPreference }, \
    { "VisualViewportEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "VisibleDebugOverlayRegions", TestHeaderKeyType::UInt32WebPreference }, \
    { "VideoQualityIncludesDisplayCompositingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "BackspaceKeyNavigationEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "MediaContainerTypesAllowedInLockdownMode", TestHeaderKeyType::StringWebPreference }, \
    { "MediaContentTypesRequiringHardwareSupport", TestHeaderKeyType::StringWebPreference }, \
    { "VideoPresentationModeAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "MediaControlsContextMenusEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "VideoPresentationManagerEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "MediaControlsScaleWithPageZoom", TestHeaderKeyType::BoolWebPreference }, \
    { "VideoFullscreenRequiresElementFullscreen", TestHeaderKeyType::BoolWebPreference }, \
    { "MediaDataLoadsAutomatically", TestHeaderKeyType::BoolWebPreference }, \
    { "MediaPreferredFullscreenWidth", TestHeaderKeyType::DoubleWebPreference }, \
    { "MediaPreloadingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "InvisibleAutoplayNotPermitted", TestHeaderKeyType::BoolWebPreference }, \
    { "InterruptVideoOnPageVisibilityChangeEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "InterruptAudioOnPageVisibilityChangeEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "VP9DecoderEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "MediaUserGestureInheritsFromDocument", TestHeaderKeyType::BoolWebPreference }, \
    { "MediaVideoCodecIDsAllowedInLockdownMode", TestHeaderKeyType::StringWebPreference }, \
    { "InteractionRegionMinimumCornerRadius", TestHeaderKeyType::DoubleWebPreference }, \
    { "InteractionRegionInlinePadding", TestHeaderKeyType::DoubleWebPreference }, \
    { "InspectorWindowFrame", TestHeaderKeyType::StringWebPreference }, \
    { "InspectorSupportsShowingCertificate", TestHeaderKeyType::BoolWebPreference }, \
    { "InspectorStartsAttached", TestHeaderKeyType::BoolWebPreference }, \
    { "InspectorMaximumResourcesContentSize", TestHeaderKeyType::UInt32WebPreference }, \
    { "InspectorAttachmentSide", TestHeaderKeyType::UInt32WebPreference }, \
    { "InspectorAttachedWidth", TestHeaderKeyType::UInt32WebPreference }, \
    { "InspectorAttachedHeight", TestHeaderKeyType::UInt32WebPreference }, \
    { "MinimumFontSize", TestHeaderKeyType::DoubleWebPreference }, \
    { "MinimumLogicalFontSize", TestHeaderKeyType::DoubleWebPreference }, \
    { "MinimumZoomFontSize", TestHeaderKeyType::DoubleWebPreference }, \
    { "MockCaptureDevicesPromptEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "MockScrollbarsControllerEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "MockScrollbarsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "InlineMediaPlaybackRequiresPlaysInlineAttribute", TestHeaderKeyType::BoolWebPreference }, \
    { "IncrementalRenderingSuppressionTimeout", TestHeaderKeyType::DoubleWebPreference }, \
    { "IncrementalPDFLoadingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "IncompleteImageBorderEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "NeedsAdobeFrameReloadingQuirk", TestHeaderKeyType::BoolWebPreference }, \
    { "InactiveMediaCaptureStreamRepromptIntervalInMinutes", TestHeaderKeyType::DoubleWebPreference }, \
    { "NeedsFrameNameFallbackToIdQuirk", TestHeaderKeyType::BoolWebPreference }, \
    { "NeedsKeyboardEventDisambiguationQuirks", TestHeaderKeyType::BoolWebPreference }, \
    { "PDFPluginEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "PDFPluginHUDEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "PDFPluginPageNumberIndicatorEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "PassiveTouchListenersAsDefaultOnDocument", TestHeaderKeyType::BoolWebPreference }, \
    { "PasswordEchoDuration", TestHeaderKeyType::DoubleWebPreference }, \
    { "PasswordEchoEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "PictographFontFamily", TestHeaderKeyType::StringWebPreference }, \
    { "PictureInPictureAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "PitchCorrectionAlgorithm", TestHeaderKeyType::UInt32WebPreference }, \
    { "PunchOutWhiteBackgroundsInDarkMode", TestHeaderKeyType::BoolWebPreference }, \
    { "RequiresPageVisibilityForVideoToBeNowPlaying", TestHeaderKeyType::BoolWebPreference }, \
    { "RequiresPageVisibilityToPlayAudio", TestHeaderKeyType::BoolWebPreference }, \
    { "HiddenPageCSSAnimationSuspensionEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "RequiresUserGestureForAudioPlayback", TestHeaderKeyType::BoolWebPreference }, \
    { "RequiresUserGestureForMediaPlayback", TestHeaderKeyType::BoolWebPreference }, \
    { "RequiresUserGestureForVideoPlayback", TestHeaderKeyType::BoolWebPreference }, \
    { "RequiresUserGestureToLoadVideo", TestHeaderKeyType::BoolWebPreference }, \
    { "UsesSingleWebProcess", TestHeaderKeyType::BoolWebPreference }, \
    { "RubberBandingForSubScrollableRegionsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "SampledPageTopColorMaxDifference", TestHeaderKeyType::DoubleWebPreference }, \
    { "SampledPageTopColorMinHeight", TestHeaderKeyType::DoubleWebPreference }, \
    { "UsesEncodingDetector", TestHeaderKeyType::BoolWebPreference }, \
    { "SansSerifFontFamily", TestHeaderKeyType::StringWebPreference }, \
    { "SelectTrailingWhitespaceEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "SerifFontFamily", TestHeaderKeyType::StringWebPreference }, \
    { "UsesBackForwardCache", TestHeaderKeyType::BoolWebPreference }, \
    { "UserInterfaceDirectionPolicy", TestHeaderKeyType::UInt32WebPreference }, \
    { "CaretBrowsingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "UseSystemAppearance", TestHeaderKeyType::BoolWebPreference }, \
    { "ServiceControlsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "GStreamerEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ServiceWorkerEntitlementDisabledForTesting", TestHeaderKeyType::BoolWebPreference }, \
    { "ShouldAllowUserInstalledFonts", TestHeaderKeyType::BoolWebPreference }, \
    { "ColorFilterEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "UsePreHTML5ParserQuirks", TestHeaderKeyType::BoolWebPreference }, \
    { "ShouldConvertInvalidURLsToBlank", TestHeaderKeyType::BoolWebPreference }, \
    { "ShouldConvertPositionStyleOnCopy", TestHeaderKeyType::BoolWebPreference }, \
    { "ShouldDecidePolicyBeforeLoadingQuickLookPreview", TestHeaderKeyType::BoolWebPreference }, \
    { "ShouldDisplayCaptions", TestHeaderKeyType::BoolWebPreference }, \
    { "ContentChangeObserverEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ContentDispositionAttachmentSandboxEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ForceWebGLUsesLowPower", TestHeaderKeyType::BoolWebPreference }, \
    { "ContextMenuQRCodeDetectionEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ShouldDisplaySubtitles", TestHeaderKeyType::BoolWebPreference }, \
    { "ForceFTPDirectoryListings", TestHeaderKeyType::BoolWebPreference }, \
    { "ForceCompositingMode", TestHeaderKeyType::BoolWebPreference }, \
    { "ShouldDisplayTextDescriptions", TestHeaderKeyType::BoolWebPreference }, \
    { "ShouldEnableTextAutosizingBoost", TestHeaderKeyType::BoolWebPreference }, \
    { "UseImageDocumentForSubframePDF", TestHeaderKeyType::BoolWebPreference }, \
    { "FixedFontFamily", TestHeaderKeyType::StringWebPreference }, \
    { "ShouldIgnoreMetaViewport", TestHeaderKeyType::BoolWebPreference }, \
    { "ShouldPrintBackgrounds", TestHeaderKeyType::BoolWebPreference }, \
    { "CursiveFontFamily", TestHeaderKeyType::StringWebPreference }, \
    { "ShouldRespectImageOrientation", TestHeaderKeyType::BoolWebPreference }, \
    { "ShouldRestrictBaseURLSchemes", TestHeaderKeyType::BoolWebPreference }, \
    { "ShouldSuppressTextInputFromEditingDuringProvisionalNavigation", TestHeaderKeyType::BoolWebPreference }, \
    { "FantasyFontFamily", TestHeaderKeyType::StringWebPreference }, \
    { "DOMPasteAllowed", TestHeaderKeyType::BoolWebPreference }, \
    { "ShouldUseServiceWorkerShortTimeout", TestHeaderKeyType::BoolWebPreference }, \
    { "FTPDirectoryTemplatePath", TestHeaderKeyType::StringWebPreference }, \
    { "DataDetectorTypes", TestHeaderKeyType::UInt32WebPreference }, \
    { "ExtensibleSSOEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "TreatsAnyTextCSSLinkAsStylesheet", TestHeaderKeyType::BoolWebPreference }, \
    { "LinkPreloadEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ShowsToolTipOverTruncatedText", TestHeaderKeyType::BoolWebPreference }, \
    { "ThreadedScrollingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "DefaultFixedFontSize", TestHeaderKeyType::DoubleWebPreference }, \
    { "DefaultFontSize", TestHeaderKeyType::DoubleWebPreference }, \
    { "DefaultTextEncodingName", TestHeaderKeyType::StringWebPreference }, \
    { "TextInteractionEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "TextExtractionEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "TextAutosizingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "DeveloperExtrasEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "DeviceHeight", TestHeaderKeyType::UInt32WebPreference }, \
    { "DeviceOrientationEventEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "DeviceOrientationPermissionAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "DeviceWidth", TestHeaderKeyType::UInt32WebPreference }, \
    { "ShowsURLsInToolTipsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "TextAreasAreResizable", TestHeaderKeyType::BoolWebPreference }, \
    { "TemporaryTileCohortRetentionEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "TelephoneNumberParsingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ShrinksStandaloneImagesToFit", TestHeaderKeyType::BoolWebPreference }, \
    { "DisabledAdaptationsMetaTagEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "DownloadAttributeEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "TabsToLinks", TestHeaderKeyType::BoolWebPreference }, \
    { "EditableLinkBehavior", TestHeaderKeyType::UInt32WebPreference }, \
    { "SystemPreviewEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "SystemLayoutDirection", TestHeaderKeyType::UInt32WebPreference }, \
    { "SuppressesIncrementalRendering", TestHeaderKeyType::BoolWebPreference }, \
    { "StandardFontFamily", TestHeaderKeyType::StringWebPreference }, \
    { "EnableInheritURIQueryComponent", TestHeaderKeyType::BoolWebPreference }, \
    { "EncryptedMediaAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "Standalone", TestHeaderKeyType::BoolWebPreference }, \
    { "SmartInsertDeleteEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "SpatialNavigationEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "SourceBufferChangeTypeEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "TargetTextPseudoElementEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ThumbAndTrackPseudoElementsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "LinkDNSPrefetchEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "SelectShowPickerEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "PageAtRuleMarginDescriptorsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "AVFoundationEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "AVKitContentSourceEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "AcceleratedFiltersEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "AccessHandleEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "DOMTestingAPIsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "AllowMediaContentTypesRequiringHardwareSupportAsFallback", TestHeaderKeyType::BoolWebPreference }, \
    { "AllowPrivacySensitiveOperationsInNonPersistentDataStores", TestHeaderKeyType::BoolWebPreference }, \
    { "AllowViewportShrinkToFitContent", TestHeaderKeyType::BoolWebPreference }, \
    { "AllowWebGLInWorkers", TestHeaderKeyType::BoolWebPreference }, \
    { "PerElementSpeakerSelectionEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ExposeSpeakersWithoutMicrophoneEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ExposeSpeakersEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "AllowTopNavigationToDataURLs", TestHeaderKeyType::BoolWebPreference }, \
    { "AllowUniversalAccessFromFileURLs", TestHeaderKeyType::BoolWebPreference }, \
    { "AlwaysAllowLocalWebarchive", TestHeaderKeyType::BoolWebPreference }, \
    { "SWVPDecodersAlwaysEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "AppBadgeEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "AppHighlightsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "AsyncFrameScrollingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "AsyncOverflowScrollingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "UseAsyncUIKitInteractions", TestHeaderKeyType::BoolWebPreference }, \
    { "AsyncClipboardAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "AttachmentElementEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "AttachmentWideLayoutEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ExtendedAudioDescriptionsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "AudioDescriptionsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "DOMAudioSessionEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "DOMAudioSessionFullEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "AutomaticallyAdjustsViewScaleUsingMinimumEffectiveDeviceWidth", TestHeaderKeyType::BoolWebPreference }, \
    { "BeaconAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "BidiContentAwarePasteEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "BlockFontServiceInWebContentSandbox", TestHeaderKeyType::BoolWebPreference }, \
    { "BlockIconServicesInWebContentSandbox", TestHeaderKeyType::BoolWebPreference }, \
    { "BlockMobileAssetInWebContentSandbox", TestHeaderKeyType::BoolWebPreference }, \
    { "BlockMobileGestaltInWebContentSandbox", TestHeaderKeyType::BoolWebPreference }, \
    { "BlockOpenDirectoryInWebContentSandbox", TestHeaderKeyType::BoolWebPreference }, \
    { "BlockWebInspectorInWebContentSandbox", TestHeaderKeyType::BoolWebPreference }, \
    { "BroadcastChannelEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "BuiltInNotificationsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSS3DTransformBackfaceVisibilityInteroperabilityEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSCounterStyleAtRuleImageSymbolsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "AccentColorEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSAnchorPositioningEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSAnchorPositioningPositionVisibilityEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "DevolvableWidgetsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSInputSecurityEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "MasonryEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "OverscrollBehaviorEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSPaintingAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSRhythmicSizingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSScrollAnchoringEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "SpringTimingFunctionEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSTreeCountingFunctionsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSTypedOMColorEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSURLModifiersEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSURLIntegrityModifierEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSUnprefixedBackdropFilterEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSAppearanceBaseEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSAxisRelativePositionKeywordsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSBackgroundClipBorderAreaEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSColorLayersEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSContrastColorEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSCornerShapeEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSDPropertyEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSDynamicRangeLimitMixEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSConstrainedDynamicRangeLimitEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSFieldSizingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSFontVariantEmojiEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSLineClampEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSLineFitEdgeEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSProgressFunctionEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSRandomFunctionEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSRubyAlignEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSRubyOverhangEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSScrollbarColorEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSScrollbarGutterEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSScrollbarWidthEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSShapeFunctionEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSTextAutospaceEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSTextBoxTrimEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSTextGroupAlignEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSTextJustifyEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSTextSpacingTrimEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSTextUnderlinePositionLeftRightEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSTextWrapPrettyEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSTransformStyleSeparatedEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CacheAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CanvasColorSpaceEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CanvasFiltersEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CanvasLayersEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CanvasUsesAcceleratedDrawing", TestHeaderKeyType::BoolWebPreference }, \
    { "CanvasPixelFormatEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ChildProcessDebuggabilityEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ClearSiteDataHTTPHeaderEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ClearSiteDataExecutionContextsSupportEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CloseWatcherEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "InputTypeColorEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CompositingBordersVisible", TestHeaderKeyType::BoolWebPreference }, \
    { "CompositingRepaintCountersVisible", TestHeaderKeyType::BoolWebPreference }, \
    { "CompressionStreamEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ContactPickerAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ContentInsetBackgroundFillEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CookieConsentAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CookieStoreManagerEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CookieStoreAPIExtendedAttributesEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CookieStoreAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CookieEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "InputMethodUsesCorrectKeyEventOrder", TestHeaderKeyType::BoolWebPreference }, \
    { "CrossDocumentViewTransitionsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CrossOriginEmbedderPolicyEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CrossOriginOpenerPolicyEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CustomPasteboardDataEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "DOMPasteAccessRequestsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "MutationEventsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "DOMTimersThrottlingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ZoomOnDoubleTapWhenRoot", TestHeaderKeyType::BoolWebPreference }, \
    { "AlwaysZoomOnDoubleTap", TestHeaderKeyType::BoolWebPreference }, \
    { "DataTransferItemsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "DataListElementEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "InputTypeDateEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "DateTimeInputsEditableComponentsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "DeclarativeWebPush", TestHeaderKeyType::BoolWebPreference }, \
    { "ShouldDeferAsynchronousScriptsUntilAfterDocumentLoadOrFirstPaint", TestHeaderKeyType::BoolWebPreference }, \
    { "DeprecationReportingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "DetachableMediaSourceEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "UAVisualTransitionDetectionEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "DiagnosticLoggingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "DigitalCredentialsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "DirectoryUploadEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "IsThirdPartyCookieBlockingDisabled", TestHeaderKeyType::BoolWebPreference }, \
    { "IsFirstPartyWebsiteDataRemovalDisabled", TestHeaderKeyType::BoolWebPreference }, \
    { "DisableScreenSizeOverride", TestHeaderKeyType::BoolWebPreference }, \
    { "ShouldDropNearSuspendedAssertionAfterDelay", TestHeaderKeyType::BoolWebPreference }, \
    { "UseCGDisplayListsForDOMRendering", TestHeaderKeyType::BoolWebPreference }, \
    { "ReplayCGDisplayListsIntoBackingStore", TestHeaderKeyType::BoolWebPreference }, \
    { "DynamicSiteInterventionsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "EmbedElementEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "EnableAccessibilityOnDemand", TestHeaderKeyType::BoolWebPreference }, \
    { "AutomaticLiveResizeEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CanvasFingerprintingQuirkEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "EnableElementCurrentCSSZoom", TestHeaderKeyType::BoolWebPreference }, \
    { "EnumeratingAllNetworkInterfacesEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "EnumeratingVisibleNetworkInterfacesEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ICECandidateFilteringEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "LegacyEncryptedMediaAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "MockCaptureDevicesEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ModelProcessEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "PDFJSViewerEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "AuxclickEventEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "BackgroundWebContentRunningBoardThrottlingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "BackgroundFetchAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "EnableDebuggingFeaturesInSandbox", TestHeaderKeyType::BoolWebPreference }, \
    { "CFNetworkNetworkLoaderEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ExperimentalSandboxEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "NavigatorUserAgentDataJavaScriptAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "BlobFileAccessEnforcementEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "EnterKeyHintEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "EventTimingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "EventHandlerDrivenSmoothKeyboardScrollingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "MediaSessionCoordinatorEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "MediaSessionPlaylistEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ExposeCaptureDevicesAfterCaptureEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ExposeDefaultSpeakerAsSpecificDeviceEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "FTPEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "PreferFasterClickOverDoubleTap", TestHeaderKeyType::BoolWebPreference }, \
    { "FasterClicksEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "FileSystemEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "FileSystemWritableStreamEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "FileReaderAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "FilterLinkDecorationByDefaultEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ForceLockdownFontParserEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ForceAlwaysUserScalable", TestHeaderKeyType::BoolWebPreference }, \
    { "FormControlRefreshEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "IFrameResourceMonitoringTestingSettingsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "IFrameResourceMonitoringEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "FullScreenKeyboardLock", TestHeaderKeyType::BoolWebPreference }, \
    { "FullScreenEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "FullscreenSceneAspectRatioLockingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "FullscreenSceneDimmingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CaptureAudioInGPUProcessEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "BlockMediaLayerRehostingInWebContentProcess", TestHeaderKeyType::BoolWebPreference }, \
    { "UseGPUProcessForCanvasRenderingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ManageCaptureStatusBarInGPUProcessEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "UseGPUProcessForDOMRenderingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "UseGPUProcessForMediaEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "UseGPUProcessForDisplayCapture", TestHeaderKeyType::BoolWebPreference }, \
    { "CaptureVideoInGPUProcessEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "UseGPUProcessForWebGLEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebRTCPlatformCodecsInGPUProcessEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "GamepadTriggerRumbleEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "GamepadVibrationActuatorEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "GamepadsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "GenericCueAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "GeolocationAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "GraphicsContextFiltersEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "AcceleratedDrawingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ModelElementEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ModelDocumentEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "InteractiveFormValidationEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "MediaEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "InputTypeColorEnhancementsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "DetailsAutoExpandEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CommandAttributesEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "HTMLLegacyAttributeValueSerializationEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "PopoverAttributeEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "SwitchControlEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "HTTPSByDefaultEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "HiddenPageDOMTimerThrottlingAutoIncreases", TestHeaderKeyType::BoolWebPreference }, \
    { "HiddenPageDOMTimerThrottlingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "HostedBlurMaterialInMediaControlsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "BlockIOKitInWebContentSandbox", TestHeaderKeyType::BoolWebPreference }, \
    { "IOSurfaceLosslessCompressionEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "IPCTestingAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ItpDebugModeEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "TextAutosizingUsesIdempotentMode", TestHeaderKeyType::BoolWebPreference }, \
    { "IgnoreInvalidMessageWhenIPCTestingAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "IgnoreIframeEmbeddingProtectionsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ImageAnalysisDuringFindInPageEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ImageAnimationControlEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ImageCaptureEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ImageControlsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "InWindowFullscreenEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "IncludeIgnoredInCoreAXTree", TestHeaderKeyType::BoolWebPreference }, \
    { "IndexedDBAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "InteractionRegionsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "IsAccessibilityIsolatedTreeEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "JavaScriptEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "KeyboardDismissalGestureEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "LayerBasedSVGEngineEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "LazyIframeLoadingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "LazyImageLoadingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "LegacyOverflowScrollingTouchEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "LegacyLineLayoutVisualCoverageEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ShowModalDialogEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "MediaCaptureRequiresSecureConnection", TestHeaderKeyType::BoolWebPreference }, \
    { "LimitedMatroskaSupportEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "LinearMediaPlayerEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "LinkSanitizerEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "LinkPreconnectEarlyHintsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "LinkPrefetchEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "LoadWebArchiveWithEphemeralStorageEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "LocalFileContentSniffingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "LocalNetworkAccessEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "LocalStorageEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "LockdownFontParserEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "LogsPageMessagesToSystemConsoleEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "LoginStatusAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "MainContentUserGestureOverrideEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ManagedMediaSourceEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ManagedMediaSourceNeedsAirPlay", TestHeaderKeyType::BoolWebPreference }, \
    { "CoreMathMLEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "MediaCapabilitiesExtensionsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "MediaCapabilityGrantsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "MediaPlaybackEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "MediaSessionEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "MediaSourceEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "MediaDevicesEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "MediaRecorderEnabledWebM", TestHeaderKeyType::BoolWebPreference }, \
    { "MediaRecorderEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "MediaSessionCaptureToggleAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "MediaSourceInWorkerEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "MediaSourcePrefersDecompressionSession", TestHeaderKeyType::BoolWebPreference }, \
    { "MediaStreamTrackProcessingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "MetaViewportInteractiveWidgetEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ModelNoPortalAttributeEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ShouldUseModernAVContentKeySession", TestHeaderKeyType::BoolWebPreference }, \
    { "MomentumScrollingAnimatorEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "InputTypeMonthEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "MouseEventsSimulationEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "MuteCameraOnMicrophoneInterruptionEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "NavigationAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "NeedsInAppBrowserPrivacyQuirks", TestHeaderKeyType::BoolWebPreference }, \
    { "NeedsSiteSpecificQuirks", TestHeaderKeyType::BoolWebPreference }, \
    { "NeedsStorageAccessFromFileURLsQuirk", TestHeaderKeyType::BoolWebPreference }, \
    { "FlexFormattingContextIntegrationEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "NotificationEventEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "NotificationsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ObservableEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "AccessibilityThreadTextApisEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "OffscreenCanvasInWorkersEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "OffscreenCanvasEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "OpportunisticSweepingAndGarbageCollectionEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "OptInPartitionedCookiesEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "OverlappingBackingStoreProvidersEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "OverlayRegionsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "PageVisibilityBasedProcessSuppressionEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "PermissionsAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "PhotoPickerPrefersOriginalImageFormat", TestHeaderKeyType::BoolWebPreference }, \
    { "PictureInPicturePlaybackStateEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "GetCoalescedEventsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "GetPredictedEventsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "PointerLockEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "PointerLockOptionsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "PreferPageRenderingUpdatesNear60FPSEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "PreferSpatialAudioExperience", TestHeaderKeyType::BoolWebPreference }, \
    { "VideoFullsceenPrefersMostVisibleHeuristic", TestHeaderKeyType::BoolWebPreference }, \
    { "PrivateClickMeasurementDebugModeEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "PrivateClickMeasurementFraudPreventionEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "PrivateClickMeasurementEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "PrivateTokenUsageByThirdPartyEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "PropagateDamagingInformation", TestHeaderKeyType::BoolWebPreference }, \
    { "PushAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "LegacyPluginQuirkForMailSignaturesEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "GoogleAntiFlickerOptimizationQuirkEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ReadableByteStreamAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "RemoteMediaSessionManagerEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "RemotePlaybackEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "RemoteSnapshottingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "RemoveBackgroundEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "RequestVideoFrameCallbackEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "RequireUAGetDisplayMediaPrompt", TestHeaderKeyType::BoolWebPreference }, \
    { "LoginStatusAPIRequiresWebAuthnEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "SpeakerSelectionRequiresUserGesture", TestHeaderKeyType::BoolWebPreference }, \
    { "FullscreenRequirementForScreenOrientationLockingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "GetUserMediaRequiresFocus", TestHeaderKeyType::BoolWebPreference }, \
    { "ResourceLoadSchedulingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ResourceUsageOverlayVisible", TestHeaderKeyType::BoolWebPreference }, \
    { "RespondToThermalPressureAggressively", TestHeaderKeyType::BoolWebPreference }, \
    { "SKAttributionEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "SafeBrowsingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "IsSameSiteStrictEnforcementEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ScopedCustomElementRegistryEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ScreenOrientationLockingAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ScreenOrientationAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ScreenTimeEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ScreenWakeLockAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ScreenCaptureEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ScriptTrackingPrivacyLoggingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ScriptTrackingPrivacyProtectionsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ScrollingPerformanceTestingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ScrollToTextFragmentFeatureDetectionEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ScrollToTextFragmentGenerationEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ScrollToTextFragmentIndicatorEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ScrollToTextFragmentMarkingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ScrollToTextFragmentEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ScrollAnimatorEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ScrollDrivenAnimationsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "SecureContextChecksEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "SelectionFlippingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "SelectionHonorsOverflowScrolling", TestHeaderKeyType::BoolWebPreference }, \
    { "ServiceWorkerInstallEventEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ServiceWorkerNavigationPreloadEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ServiceWorkersEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ShapeDetection", TestHeaderKeyType::BoolWebPreference }, \
    { "SiteIsolationSharedProcessEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "SharedWorkerEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ShowMediaStatsContextMenuItemEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ShowFrameProcessBordersEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "SidewaysWritingModesEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "SiteIsolationEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "SpatialImageControlsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "SpeechRecognitionEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "SpeechSynthesisAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "StorageAPIEstimateEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "StorageAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "StorageBlockingPolicy", TestHeaderKeyType::UInt32WebPreference }, \
    { "SupportHDRCompositorTonemappingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "SupportHDRDisplayEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ProcessSwapOnCrossSiteNavigationEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ShouldTakeNearSuspendedAssertions", TestHeaderKeyType::BoolWebPreference }, \
    { "TextAnimationsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "TextRecognitionInVideosEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "TextTracksInMSEEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ThreadedAnimationResolutionEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "TiledScrollingIndicatorVisible", TestHeaderKeyType::BoolWebPreference }, \
    { "InputTypeTimeEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "TopContentInsetBackgroundCanChangeAfterScrolling", TestHeaderKeyType::BoolWebPreference }, \
    { "TouchInputCompatibilityEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "TrackConfigurationEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "TrustedTypesEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "URLPatternAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "UndoManagerAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "UnifiedPDFEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "UnifyDamagedRegions", TestHeaderKeyType::BoolWebPreference }, \
    { "IPAddressAndLocalhostMixedContentUpgradeTestingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "UpgradeKnownHostsToHTTPSEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "UpgradeMixedContentEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "UseARKitForModel", TestHeaderKeyType::BoolWebPreference }, \
    { "UseAVCaptureDeviceRotationCoordinatorAPI", TestHeaderKeyType::BoolWebPreference }, \
    { "UseIFCForSVGText", TestHeaderKeyType::BoolWebPreference }, \
    { "UseMicrophoneMuteStatusAPI", TestHeaderKeyType::BoolWebPreference }, \
    { "UseSceneKitForModel", TestHeaderKeyType::BoolWebPreference }, \
    { "UseGiantTiles", TestHeaderKeyType::BoolWebPreference }, \
    { "UseDamagingInformationForCompositing", TestHeaderKeyType::BoolWebPreference }, \
    { "UserActivationAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "UserGesturePromisePropagationEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "UsesWebContentRestrictionsForFilter", TestHeaderKeyType::BoolWebPreference }, \
    { "ServiceWorkersUserGestureEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "VerifyWindowOpenUserGestureFromUIProcess", TestHeaderKeyType::BoolWebPreference }, \
    { "VerticalFormControlsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "VideoRendererProtectedFallbackDisabled", TestHeaderKeyType::BoolWebPreference }, \
    { "VideoRendererUseDecompressionSessionForProtected", TestHeaderKeyType::BoolWebPreference }, \
    { "ViewTransitionClassesEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ViewTransitionTypesEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ViewTransitionsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ViewGestureDebuggingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "VisualTranslationEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "VisualViewportAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "VisuallyContiguousBidiTextSelectionEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebAPIStatisticsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebAPIsInShadowRealmEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebAnimationsOverallProgressPropertyEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebAnimationsCustomEffectsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebAnimationsCustomFrameRateEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebArchiveDebugModeEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebArchiveTestingModeEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebAuthenticationASEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebAuthenticationEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebCryptoSafeCurvesEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebCryptoX25519Enabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebLocksAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebShareFileAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebShareEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebAssemblyESMIntegrationEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebCodecsAV1Enabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebCodecsAudioEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebCodecsHEVCEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebCodecsVideoEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebExtensionBookmarksEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebExtensionSidebarEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebGLDraftExtensionsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebGLTimerQueriesEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebGLEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebGPUHDREnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebXRWebGPUBindingsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebGPUEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebInspectorEngineeringSettingsAllowed", TestHeaderKeyType::BoolWebPreference }, \
    { "WebRTCAV1CodecEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebRTCAudioLatencyAdaptationEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebRTCDTMFEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebRTCEncodedTransformEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebRTCH264HardwareEncoderEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebRTCH265CodecEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebRTCL4SEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebRTCMediaPipelineAdditionalLoggingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "LegacyWebRTCOfferOptionsEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "PeerConnectionVideoScalingAdaptationDisabled", TestHeaderKeyType::BoolWebPreference }, \
    { "PeerConnectionEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebRTCRemoteVideoFrameEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebRTCSFrameTransformEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebRTCSocketsProxyingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebRTCUDPPortRange", TestHeaderKeyType::StringWebPreference }, \
    { "WebRTCVP9Profile0CodecEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebRTCVP9Profile2CodecEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebRTCInterfaceMonitoringViaNWEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebTransportEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebXRAugmentedRealityModuleEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebXREnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebXRGamepadsModuleEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebXRHandInputModuleEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebXRLayersAPIEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WebPageSpatialBackdropEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "InputTypeWeekEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WheelEventGesturesBecomeNonBlocking", TestHeaderKeyType::BoolWebPreference }, \
    { "PassiveWheelListenersAsDefaultOnDocument", TestHeaderKeyType::BoolWebPreference }, \
    { "WorkerAsynchronousURLErrorHandlingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "WriteRichTextDataWhenCopyingOrDragging", TestHeaderKeyType::BoolWebPreference }, \
    { "WritingSuggestionsAttributeEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "XSLTEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "IsFirstPartyWebsiteDataRemovalLiveOnTestingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "IsFirstPartyWebsiteDataRemovalReproTestingEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "AltitudeAngleEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "AzimuthAngleEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "InputTypeDateTimeLocalEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CaretPositionFromPointEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "HiddenUntilFoundEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "HTTPEquivEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "ShadowRootReferenceTargetEnabledForAriaOwns", TestHeaderKeyType::BoolWebPreference }, \
    { "ShadowRootReferenceTargetEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "RequestIdleCallbackEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "RequestStorageAccessThrowsExceptionUntilReload", TestHeaderKeyType::BoolWebPreference }, \
    { "ScrollendEventEnabled", TestHeaderKeyType::BoolWebPreference }, \
    { "CSSWordBreakAutoPhraseEnabled", TestHeaderKeyType::BoolWebPreference }, \
    \

