#include "RemoteBarcodeDetectorMessageReceiver.cpp"
#include "RemoteBindGroupLayoutMessageReceiver.cpp"
#include "RemoteBindGroupMessageReceiver.cpp"
#include "RemoteBufferMessageReceiver.cpp"
#include "RemoteCommandBufferMessageReceiver.cpp"
#include "RemoteCommandEncoderMessageReceiver.cpp"
#include "RemoteCompositorIntegrationMessageReceiver.cpp"
#include "RemoteComputePassEncoderMessageReceiver.cpp"
