#include "WebProcess/GPU/graphics/RemoteGraphicsContextGLProxy.cpp"
#include "WebProcess/GPU/graphics/RemoteGraphicsContextGLProxyFunctionsGenerated.cpp"
#include "WebProcess/GPU/graphics/RemoteImageBufferProxy.cpp"
#include "WebProcess/GPU/graphics/RemoteImageBufferSetProxy.cpp"
#include "WebProcess/GPU/graphics/RemoteNativeImageBackendProxy.cpp"
#include "WebProcess/GPU/graphics/RemoteRenderingBackendProxy.cpp"
#include "WebProcess/GPU/graphics/RemoteResourceCacheProxy.cpp"
#include "WebProcess/GPU/graphics/WebGPU/RemoteAdapterProxy.cpp"
