#include "WebProcess/WebCoreSupport/WebPlatformStrategies.cpp"
#include "WebProcess/WebCoreSupport/WebPopupMenu.cpp"
#include "WebProcess/WebCoreSupport/WebProcessSyncClient.cpp"
#include "WebProcess/WebCoreSupport/WebProgressTrackerClient.cpp"
#include "WebProcess/WebCoreSupport/WebRemoteFrameClient.cpp"
#include "WebProcess/WebCoreSupport/WebResourceLoadObserver.cpp"
#include "WebProcess/WebCoreSupport/WebScreenOrientationManager.cpp"
#include "WebProcess/WebCoreSupport/WebSearchPopupMenu.cpp"
