#include "Shared/WebGPU/WebGPUValidationError.cpp"
#include "Shared/WebGPU/WebGPUVertexAttribute.cpp"
#include "Shared/WebGPU/WebGPUVertexBufferLayout.cpp"
#include "Shared/WebGPU/WebGPUVertexState.cpp"
#include "Shared/WebsiteData/WebsiteData.cpp"
#include "Shared/XR/XRDeviceProxy.cpp"
#include "Shared/graphics/ImageBufferSet.cpp"
