#include "RemoteGraphicsContextGLProxyMessageReceiver.cpp"
#include "RemotePipelineLayoutMessageReceiver.cpp"
#include "RemotePresentationContextMessageReceiver.cpp"
#include "RemoteQuerySetMessageReceiver.cpp"
#include "RemoteQueueMessageReceiver.cpp"
#include "RemoteRenderBundleEncoderMessageReceiver.cpp"
#include "RemoteRenderBundleMessageReceiver.cpp"
#include "RemoteRenderPassEncoderMessageReceiver.cpp"
