#include "Modules/notifications/Notification.cpp"
#include "Modules/notifications/NotificationController.cpp"
#include "Modules/notifications/NotificationData.cpp"
#include "Modules/notifications/NotificationEvent.cpp"
#include "Modules/notifications/NotificationJSONParser.cpp"
#include "Modules/notifications/NotificationPayload.cpp"
#include "Modules/notifications/NotificationResourcesLoader.cpp"
#include "Modules/paymentrequest/MerchantValidationEvent.cpp"
