#include "JSBackgroundFetchManager.cpp"
#include "JSBackgroundFetchOptions.cpp"
#include "JSBackgroundFetchRecord.cpp"
#include "JSBackgroundFetchRegistration.cpp"
#include "JSBackgroundFetchResult.cpp"
#include "JSBackgroundFetchUIOptions.cpp"
#include "JSBackgroundFetchUpdateUIEvent.cpp"
#include "JSBarProp.cpp"
