#include "Modules/webxr/WebXRJointPose.cpp"
#include "Modules/webxr/WebXRJointSpace.cpp"
#include "Modules/webxr/WebXRLayer.cpp"
#include "Modules/webxr/WebXROpaqueFramebuffer.cpp"
#include "Modules/webxr/WebXRPose.cpp"
#include "Modules/webxr/WebXRReferenceSpace.cpp"
#include "Modules/webxr/WebXRRenderState.cpp"
#include "Modules/webxr/WebXRRigidTransform.cpp"
