#include "style/values/shapes/StylePathOperationWrappers.cpp"
#include "style/values/shapes/StylePolygonFunction.cpp"
#include "style/values/shapes/StyleRectFunction.cpp"
#include "style/values/shapes/StyleShapeFunction.cpp"
#include "style/values/shapes/StyleShapeOutside.cpp"
#include "style/values/shapes/StyleXywhFunction.cpp"
#include "style/values/size-adjust/StyleTextSizeAdjust.cpp"
#include "style/values/sizing/StyleAspectRatio.cpp"
