#include "Modules/webxr/NavigatorWebXR.cpp"
#include "Modules/webxr/WebXRBoundedReferenceSpace.cpp"
#include "Modules/webxr/WebXRFrame.cpp"
#include "Modules/webxr/WebXRGamepad.cpp"
#include "Modules/webxr/WebXRHand.cpp"
#include "Modules/webxr/WebXRInputSource.cpp"
#include "Modules/webxr/WebXRInputSourceArray.cpp"
#include "Modules/webxr/WebXRInputSpace.cpp"
