#include "Modules/reporting/Report.cpp"
#include "Modules/reporting/ReportBody.cpp"
#include "Modules/reporting/ReportingObserver.cpp"
#include "Modules/reporting/ReportingScope.cpp"
#include "Modules/reporting/TestReportBody.cpp"
#include "Modules/screen-wake-lock/NavigatorScreenWakeLock.cpp"
#include "Modules/screen-wake-lock/WakeLock.cpp"
#include "Modules/screen-wake-lock/WakeLockManager.cpp"
