#include "bindings/js/JSPopStateEventCustom.cpp"
#include "bindings/js/JSPromiseRejectionEventCustom.cpp"
#include "bindings/js/JSRTCRtpSFrameTransformCustom.cpp"
#include "bindings/js/JSRangeCustom.cpp"
#include "bindings/js/JSReadableStreamSourceCustom.cpp"
#include "bindings/js/JSReportBodyCustom.cpp"
#include "bindings/js/JSReportingObserverCustom.cpp"
#include "bindings/js/JSResizeObserverCustom.cpp"
