#include "platform/mock/DeviceOrientationClientMock.cpp"
#include "platform/mock/GeolocationClientMock.cpp"
#include "platform/mock/MediaEngineConfigurationFactoryMock.cpp"
#include "platform/mock/MockRealtimeAudioSource.cpp"
#include "platform/mock/MockRealtimeMediaSourceCenter.cpp"
#include "platform/mock/MockRealtimeVideoSource.cpp"
#include "platform/mock/PlatformSpeechSynthesizerMock.cpp"
#include "platform/mock/RTCDataChannelHandlerMock.cpp"
