#include "b3/B3Value.cpp"
#include "b3/B3ValueKey.cpp"
#include "b3/B3ValueRep.cpp"
#include "b3/B3Variable.cpp"
#include "b3/B3VariableLiveness.cpp"
#include "b3/B3VariableValue.cpp"
#include "b3/B3WasmAddressValue.cpp"
#include "b3/B3WasmBoundsCheckValue.cpp"
