partial interface DedicatedWorkerGlobalScope {
    [EnabledBySetting=CompressionStreamEnabled] attribute CompressionStreamConstructor CompressionStream;
    [EnabledBySetting=CompressionStreamEnabled, PrivateIdentifier] attribute CompressionStreamEncoderConstructor CompressionStreamEncoder;
    [EnabledBySetting=CompressionStreamEnabled] attribute DecompressionStreamConstructor DecompressionStream;
    [EnabledBySetting=CompressionStreamEnabled, PrivateIdentifier] attribute DecompressionStreamDecoderConstructor DecompressionStreamDecoder;
    [EnabledBySetting=AccessHandleEnabled, SecureContext] attribute FileSystemSyncAccessHandleConstructor FileSystemSyncAccessHandle;
    [EnabledBySetting=MediaCapabilitiesEnabled] attribute MediaCapabilitiesConstructor MediaCapabilities;
    [Conditional=MEDIA_SOURCE&MEDIA_SOURCE_IN_WORKERS, EnabledBySetting=ManagedMediaSourceEnabled] attribute BufferedChangeEventConstructor BufferedChangeEvent;
    [Conditional=MEDIA_SOURCE&MEDIA_SOURCE_IN_WORKERS, EnabledBySetting=ManagedMediaSourceEnabled, EnabledForContext] attribute ManagedMediaSourceConstructor ManagedMediaSource;
    [Conditional=MEDIA_SOURCE&MEDIA_SOURCE_IN_WORKERS, EnabledBySetting=ManagedMediaSourceEnabled] attribute ManagedSourceBufferConstructor ManagedSourceBuffer;
    [Conditional=MEDIA_SOURCE&MEDIA_SOURCE_IN_WORKERS, EnabledBySetting=MediaSourceEnabled, EnabledForContext] attribute MediaSourceConstructor MediaSource;
    [Conditional=MEDIA_SOURCE_IN_WORKERS, EnabledBySetting=MediaSourceInWorkerEnabled] attribute MediaSourceHandleConstructor MediaSourceHandle;
    [Conditional=MEDIA_SOURCE&MEDIA_SOURCE_IN_WORKERS, EnabledBySetting=MediaSourceEnabled, EnabledForContext] attribute SourceBufferConstructor SourceBuffer;
    [Conditional=MEDIA_STREAM, PrivateIdentifier, PublicIdentifier] attribute MediaStreamTrackConstructor MediaStreamTrack;
    [Conditional=MEDIA_STREAM&WEB_CODECS, EnabledBySetting=MediaStreamTrackProcessingEnabled, PrivateIdentifier, PublicIdentifier] attribute MediaStreamTrackProcessorConstructor MediaStreamTrackProcessor;
    [Conditional=WEB_RTC, EnabledBySetting=WebRTCEncodedTransformEnabled] attribute RTCEncodedAudioFrameConstructor RTCEncodedAudioFrame;
    [Conditional=WEB_RTC, EnabledBySetting=WebRTCEncodedTransformEnabled] attribute RTCEncodedVideoFrameConstructor RTCEncodedVideoFrame;
    [Conditional=WEB_RTC, EnabledBySetting=WebRTCSFrameTransformEnabled] attribute RTCRtpSFrameTransformConstructor SFrameTransform;
    [Conditional=WEB_RTC, EnabledBySetting=WebRTCSFrameTransformEnabled] attribute RTCRtpSFrameTransformErrorEventConstructor SFrameTransformErrorEvent;
    [Conditional=WEB_RTC, EnabledBySetting=WebRTCEncodedTransformEnabled] attribute RTCRtpScriptTransformerConstructor RTCRtpScriptTransformer;
    [Conditional=MEDIA_STREAM&WEB_CODECS, EnabledBySetting=MediaStreamTrackProcessingEnabled, PrivateIdentifier, PublicIdentifier] attribute VideoTrackGeneratorConstructor VideoTrackGenerator;
    [Conditional=NOTIFICATIONS, EnabledBySetting=NotificationsEnabled] attribute NotificationConstructor Notification;
    [EnabledBySetting=PermissionsAPIEnabled] attribute PermissionStatusConstructor PermissionStatus;
    attribute ByteLengthQueuingStrategyConstructor ByteLengthQueuingStrategy;
    attribute CountQueuingStrategyConstructor CountQueuingStrategy;
    [PrivateIdentifier] attribute ReadableByteStreamControllerConstructor ReadableByteStreamController;
    [PrivateIdentifier, PublicIdentifier] attribute ReadableStreamConstructor ReadableStream;
    [PrivateIdentifier] attribute ReadableStreamBYOBReaderConstructor ReadableStreamBYOBReader;
    [PrivateIdentifier] attribute ReadableStreamBYOBRequestConstructor ReadableStreamBYOBRequest;
    [PrivateIdentifier, PublicIdentifier] attribute ReadableStreamDefaultControllerConstructor ReadableStreamDefaultController;
    [PrivateIdentifier, PublicIdentifier] attribute ReadableStreamDefaultReaderConstructor ReadableStreamDefaultReader;
    [PrivateIdentifier, PublicIdentifier] attribute TransformStreamConstructor TransformStream;
    [PrivateIdentifier, PublicIdentifier] attribute TransformStreamDefaultControllerConstructor TransformStreamDefaultController;
    [PrivateIdentifier, PublicIdentifier] attribute WritableStreamConstructor WritableStream;
    [PrivateIdentifier, PublicIdentifier] attribute WritableStreamDefaultControllerConstructor WritableStreamDefaultController;
    [PrivateIdentifier, PublicIdentifier] attribute WritableStreamDefaultWriterConstructor WritableStreamDefaultWriter;
    [Conditional=WEB_CODECS, EnabledBySetting=WebCodecsAudioEnabled] attribute WebCodecsAudioDataConstructor AudioData;
    [Conditional=WEB_CODECS, EnabledBySetting=WebCodecsAudioEnabled] attribute WebCodecsAudioDecoderConstructor AudioDecoder;
    [Conditional=WEB_CODECS, EnabledBySetting=WebCodecsAudioEnabled] attribute WebCodecsAudioEncoderConstructor AudioEncoder;
    [Conditional=WEB_CODECS, EnabledBySetting=WebCodecsAudioEnabled] attribute WebCodecsEncodedAudioChunkConstructor EncodedAudioChunk;
    [Conditional=WEB_CODECS, EnabledBySetting=WebCodecsVideoEnabled] attribute WebCodecsEncodedVideoChunkConstructor EncodedVideoChunk;
    [Conditional=WEB_CODECS, EnabledBySetting=WebCodecsVideoEnabled] attribute WebCodecsVideoDecoderConstructor VideoDecoder;
    [Conditional=WEB_CODECS, EnabledBySetting=WebCodecsVideoEnabled] attribute WebCodecsVideoEncoderConstructor VideoEncoder;
    [Conditional=WEB_CODECS, EnabledBySetting=WebCodecsVideoEnabled] attribute WebCodecsVideoFrameConstructor VideoFrame;
    attribute AbortControllerConstructor AbortController;
    [PrivateIdentifier, PublicIdentifier] attribute AbortSignalConstructor AbortSignal;
    attribute CustomEventConstructor CustomEvent;
    attribute ErrorEventConstructor ErrorEvent;
    attribute EventConstructor Event;
    attribute EventTargetConstructor EventTarget;
    attribute PromiseRejectionEventConstructor PromiseRejectionEvent;
    attribute TextDecoderConstructor TextDecoder;
    attribute TextDecoderStreamConstructor TextDecoderStream;
    attribute TextEncoderConstructor TextEncoder;
    attribute TextEncoderStreamConstructor TextEncoderStream;
    [EnabledBySetting=FileReaderAPIEnabled] attribute FileReaderSyncConstructor FileReaderSync;
    attribute DOMURLConstructor URL;
    attribute URLSearchParamsConstructor URLSearchParams;
    attribute PerformanceConstructor Performance;
    attribute PerformanceEntryConstructor PerformanceEntry;
    attribute PerformanceMarkConstructor PerformanceMark;
    attribute PerformanceMeasureConstructor PerformanceMeasure;
    attribute PerformanceObserverConstructor PerformanceObserver;
    attribute PerformanceObserverEntryListConstructor PerformanceObserverEntryList;
    attribute PerformanceResourceTimingConstructor PerformanceResourceTiming;
    attribute PerformanceServerTimingConstructor PerformanceServerTiming;
    attribute DedicatedWorkerGlobalScopeConstructor DedicatedWorkerGlobalScope;
    attribute WorkerConstructor Worker;
    attribute XMLHttpRequestConstructor XMLHttpRequest;
};
