/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include "config.h"

#if ENABLE(WEB_AUTHN)

#include "JSPublicKeyCredentialUserEntityJSON.h"

#include "JSDOMConvertStrings.h"
#include <JavaScriptCore/JSCInlines.h>



namespace WebCore {
using namespace JSC;

#if ENABLE(WEB_AUTHN)

template<> ConversionResult<IDLDictionary<PublicKeyCredentialUserEntityJSON>> convertDictionary<PublicKeyCredentialUserEntityJSON>(JSGlobalObject& lexicalGlobalObject, JSValue value)
{
    SUPPRESS_UNCOUNTED_LOCAL auto& vm = JSC::getVM(&lexicalGlobalObject);
    auto throwScope = DECLARE_THROW_SCOPE(vm);
    bool isNullOrUndefined = value.isUndefinedOrNull();
    auto* object = isNullOrUndefined ? nullptr : value.getObject();
    if (!isNullOrUndefined && !object) [[unlikely]] {
        throwTypeError(&lexicalGlobalObject, throwScope);
        return ConversionResultException { };
    }
    PublicKeyCredentialUserEntityJSON result;
    JSValue displayNameValue;
    if (isNullOrUndefined)
        displayNameValue = jsUndefined();
    else {
        displayNameValue = object->get(&lexicalGlobalObject, Identifier::fromString(vm, "displayName"_s));
        RETURN_IF_EXCEPTION(throwScope, ConversionResultException { });
    }
    if (displayNameValue.isUndefined()) {
        throwRequiredMemberTypeError(lexicalGlobalObject, throwScope, "displayName"_s, "PublicKeyCredentialUserEntityJSON"_s, "DOMString"_s);
        return ConversionResultException { };
    }
    auto displayNameConversionResult = convert<IDLDOMString>(lexicalGlobalObject, displayNameValue);
    if (displayNameConversionResult.hasException(throwScope)) [[unlikely]]
        return ConversionResultException { };
    result.displayName = displayNameConversionResult.releaseReturnValue();
    JSValue idValue;
    if (isNullOrUndefined)
        idValue = jsUndefined();
    else {
        idValue = object->get(&lexicalGlobalObject, Identifier::fromString(vm, "id"_s));
        RETURN_IF_EXCEPTION(throwScope, ConversionResultException { });
    }
    if (idValue.isUndefined()) {
        throwRequiredMemberTypeError(lexicalGlobalObject, throwScope, "id"_s, "PublicKeyCredentialUserEntityJSON"_s, "DOMString"_s);
        return ConversionResultException { };
    }
    auto idConversionResult = convert<IDLDOMString>(lexicalGlobalObject, idValue);
    if (idConversionResult.hasException(throwScope)) [[unlikely]]
        return ConversionResultException { };
    result.id = idConversionResult.releaseReturnValue();
    JSValue nameValue;
    if (isNullOrUndefined)
        nameValue = jsUndefined();
    else {
        nameValue = object->get(&lexicalGlobalObject, Identifier::fromString(vm, "name"_s));
        RETURN_IF_EXCEPTION(throwScope, ConversionResultException { });
    }
    if (nameValue.isUndefined()) {
        throwRequiredMemberTypeError(lexicalGlobalObject, throwScope, "name"_s, "PublicKeyCredentialUserEntityJSON"_s, "DOMString"_s);
        return ConversionResultException { };
    }
    auto nameConversionResult = convert<IDLDOMString>(lexicalGlobalObject, nameValue);
    if (nameConversionResult.hasException(throwScope)) [[unlikely]]
        return ConversionResultException { };
    result.name = nameConversionResult.releaseReturnValue();
    return result;
}

#endif

} // namespace WebCore


#endif // ENABLE(WEB_AUTHN)
