/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include "config.h"

#if ENABLE(WEB_RTC)

#include "JSRTCRtpTransceiver.h"

#include "ActiveDOMObject.h"
#include "ContextDestructionObserverInlines.h"
#include "ExtendedDOMClientIsoSubspaces.h"
#include "ExtendedDOMIsoSubspaces.h"
#include "IDLTypes.h"
#include "JSDOMAttribute.h"
#include "JSDOMBinding.h"
#include "JSDOMConstructorNotConstructable.h"
#include "JSDOMConvertBase.h"
#include "JSDOMConvertBoolean.h"
#include "JSDOMConvertDictionary.h"
#include "JSDOMConvertEnumeration.h"
#include "JSDOMConvertInterface.h"
#include "JSDOMConvertNullable.h"
#include "JSDOMConvertSequences.h"
#include "JSDOMConvertStrings.h"
#include "JSDOMExceptionHandling.h"
#include "JSDOMGlobalObject.h"
#include "JSDOMGlobalObjectInlines.h"
#include "JSDOMOperation.h"
#include "JSDOMWrapperCache.h"
#include "JSRTCRtpCodecCapability.h"
#include "JSRTCRtpReceiver.h"
#include "JSRTCRtpSender.h"
#include "JSRTCRtpTransceiverDirection.h"
#include "ScriptExecutionContext.h"
#include "WebCoreJSClientData.h"
#include <JavaScriptCore/FunctionPrototype.h>
#include <JavaScriptCore/HeapAnalyzer.h>
#include <JavaScriptCore/JSArray.h>
#include <JavaScriptCore/JSCInlines.h>
#include <JavaScriptCore/JSDestructibleObjectHeapCellType.h>
#include <JavaScriptCore/SlotVisitorMacros.h>
#include <JavaScriptCore/SubspaceInlines.h>
#include <wtf/GetPtr.h>
#include <wtf/PointerPreparations.h>
#include <wtf/URL.h>
#include <wtf/text/MakeString.h>

namespace WebCore {
using namespace JSC;

// Functions

static JSC_DECLARE_HOST_FUNCTION(jsRTCRtpTransceiverPrototypeFunction_stop);
static JSC_DECLARE_HOST_FUNCTION(jsRTCRtpTransceiverPrototypeFunction_setCodecPreferences);

// Attributes

static JSC_DECLARE_CUSTOM_GETTER(jsRTCRtpTransceiverConstructor);
static JSC_DECLARE_CUSTOM_GETTER(jsRTCRtpTransceiver_mid);
static JSC_DECLARE_CUSTOM_GETTER(jsRTCRtpTransceiver_sender);
static JSC_DECLARE_CUSTOM_GETTER(jsRTCRtpTransceiver_receiver);
static JSC_DECLARE_CUSTOM_GETTER(jsRTCRtpTransceiver_stopped);
static JSC_DECLARE_CUSTOM_GETTER(jsRTCRtpTransceiver_direction);
static JSC_DECLARE_CUSTOM_SETTER(setJSRTCRtpTransceiver_direction);
static JSC_DECLARE_CUSTOM_GETTER(jsRTCRtpTransceiver_currentDirection);

class JSRTCRtpTransceiverPrototype final : public JSC::JSNonFinalObject {
public:
    using Base = JSC::JSNonFinalObject;
    static JSRTCRtpTransceiverPrototype* create(JSC::VM& vm, JSDOMGlobalObject* globalObject, JSC::Structure* structure)
    {
        JSRTCRtpTransceiverPrototype* ptr = new (NotNull, JSC::allocateCell<JSRTCRtpTransceiverPrototype>(vm)) JSRTCRtpTransceiverPrototype(vm, globalObject, structure);
        ptr->finishCreation(vm);
        return ptr;
    }

    DECLARE_INFO;
    template<typename CellType, JSC::SubspaceAccess>
    static JSC::GCClient::IsoSubspace* subspaceFor(JSC::VM& vm)
    {
        STATIC_ASSERT_ISO_SUBSPACE_SHARABLE(JSRTCRtpTransceiverPrototype, Base);
        return &vm.plainObjectSpace();
    }
    static JSC::Structure* createStructure(JSC::VM& vm, JSC::JSGlobalObject* globalObject, JSC::JSValue prototype)
    {
        return JSC::Structure::create(vm, globalObject, prototype, JSC::TypeInfo(JSC::ObjectType, StructureFlags), info());
    }

private:
    JSRTCRtpTransceiverPrototype(JSC::VM& vm, JSC::JSGlobalObject*, JSC::Structure* structure)
        : JSC::JSNonFinalObject(vm, structure)
    {
    }

    void finishCreation(JSC::VM&);
};
STATIC_ASSERT_ISO_SUBSPACE_SHARABLE(JSRTCRtpTransceiverPrototype, JSRTCRtpTransceiverPrototype::Base);

using JSRTCRtpTransceiverDOMConstructor = JSDOMConstructorNotConstructable<JSRTCRtpTransceiver>;

template<> const ClassInfo JSRTCRtpTransceiverDOMConstructor::s_info = { "RTCRtpTransceiver"_s, &Base::s_info, nullptr, nullptr, CREATE_METHOD_TABLE(JSRTCRtpTransceiverDOMConstructor) };

template<> JSValue JSRTCRtpTransceiverDOMConstructor::prototypeForStructure(JSC::VM& vm, const JSDOMGlobalObject& globalObject)
{
    UNUSED_PARAM(vm);
    return globalObject.functionPrototype();
}

template<> void JSRTCRtpTransceiverDOMConstructor::initializeProperties(VM& vm, JSDOMGlobalObject& globalObject)
{
    putDirect(vm, vm.propertyNames->length, jsNumber(0), JSC::PropertyAttribute::ReadOnly | JSC::PropertyAttribute::DontEnum);
    JSString* nameString = jsNontrivialString(vm, "RTCRtpTransceiver"_s);
    m_originalName.set(vm, this, nameString);
    putDirect(vm, vm.propertyNames->name, nameString, JSC::PropertyAttribute::ReadOnly | JSC::PropertyAttribute::DontEnum);
    putDirect(vm, vm.propertyNames->prototype, JSRTCRtpTransceiver::prototype(vm, globalObject), JSC::PropertyAttribute::ReadOnly | JSC::PropertyAttribute::DontEnum | JSC::PropertyAttribute::DontDelete);
}

/* Hash table for prototype */

static const std::array<HashTableValue, 9> JSRTCRtpTransceiverPrototypeTableValues {
    HashTableValue { "constructor"_s, static_cast<unsigned>(PropertyAttribute::DontEnum), NoIntrinsic, { HashTableValue::GetterSetterType, jsRTCRtpTransceiverConstructor, 0 } },
    HashTableValue { "mid"_s, JSC::PropertyAttribute::ReadOnly | JSC::PropertyAttribute::CustomAccessor | JSC::PropertyAttribute::DOMAttribute, NoIntrinsic, { HashTableValue::GetterSetterType, jsRTCRtpTransceiver_mid, 0 } },
    HashTableValue { "sender"_s, JSC::PropertyAttribute::ReadOnly | JSC::PropertyAttribute::CustomAccessor | JSC::PropertyAttribute::DOMAttribute, NoIntrinsic, { HashTableValue::GetterSetterType, jsRTCRtpTransceiver_sender, 0 } },
    HashTableValue { "receiver"_s, JSC::PropertyAttribute::ReadOnly | JSC::PropertyAttribute::CustomAccessor | JSC::PropertyAttribute::DOMAttribute, NoIntrinsic, { HashTableValue::GetterSetterType, jsRTCRtpTransceiver_receiver, 0 } },
    HashTableValue { "stopped"_s, JSC::PropertyAttribute::ReadOnly | JSC::PropertyAttribute::CustomAccessor | JSC::PropertyAttribute::DOMAttribute, NoIntrinsic, { HashTableValue::GetterSetterType, jsRTCRtpTransceiver_stopped, 0 } },
    HashTableValue { "direction"_s, JSC::PropertyAttribute::CustomAccessor | JSC::PropertyAttribute::DOMAttribute, NoIntrinsic, { HashTableValue::GetterSetterType, jsRTCRtpTransceiver_direction, setJSRTCRtpTransceiver_direction } },
    HashTableValue { "currentDirection"_s, JSC::PropertyAttribute::ReadOnly | JSC::PropertyAttribute::CustomAccessor | JSC::PropertyAttribute::DOMAttribute, NoIntrinsic, { HashTableValue::GetterSetterType, jsRTCRtpTransceiver_currentDirection, 0 } },
    HashTableValue { "stop"_s, static_cast<unsigned>(JSC::PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, jsRTCRtpTransceiverPrototypeFunction_stop, 0 } },
    HashTableValue { "setCodecPreferences"_s, static_cast<unsigned>(JSC::PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, jsRTCRtpTransceiverPrototypeFunction_setCodecPreferences, 1 } },
};

const ClassInfo JSRTCRtpTransceiverPrototype::s_info = { "RTCRtpTransceiver"_s, &Base::s_info, nullptr, nullptr, CREATE_METHOD_TABLE(JSRTCRtpTransceiverPrototype) };

void JSRTCRtpTransceiverPrototype::finishCreation(VM& vm)
{
    Base::finishCreation(vm);
    reifyStaticProperties(vm, JSRTCRtpTransceiver::info(), JSRTCRtpTransceiverPrototypeTableValues, *this);
    JSC_TO_STRING_TAG_WITHOUT_TRANSITION();
}

const ClassInfo JSRTCRtpTransceiver::s_info = { "RTCRtpTransceiver"_s, &Base::s_info, nullptr, nullptr, CREATE_METHOD_TABLE(JSRTCRtpTransceiver) };

JSRTCRtpTransceiver::JSRTCRtpTransceiver(Structure* structure, JSDOMGlobalObject& globalObject, Ref<RTCRtpTransceiver>&& impl)
    : JSDOMWrapper<RTCRtpTransceiver>(structure, globalObject, WTFMove(impl))
{
}

static_assert(!std::is_base_of<ActiveDOMObject, RTCRtpTransceiver>::value, "Interface is not marked as [ActiveDOMObject] even though implementation class subclasses ActiveDOMObject.");

JSObject* JSRTCRtpTransceiver::createPrototype(VM& vm, JSDOMGlobalObject& globalObject)
{
    auto* structure = JSRTCRtpTransceiverPrototype::createStructure(vm, &globalObject, globalObject.objectPrototype());
    structure->setMayBePrototype(true);
    return JSRTCRtpTransceiverPrototype::create(vm, &globalObject, structure);
}

JSObject* JSRTCRtpTransceiver::prototype(VM& vm, JSDOMGlobalObject& globalObject)
{
    return getDOMPrototype<JSRTCRtpTransceiver>(vm, globalObject);
}

JSValue JSRTCRtpTransceiver::getConstructor(VM& vm, const JSGlobalObject* globalObject)
{
    return getDOMConstructor<JSRTCRtpTransceiverDOMConstructor, DOMConstructorID::RTCRtpTransceiver>(vm, *jsCast<const JSDOMGlobalObject*>(globalObject));
}

void JSRTCRtpTransceiver::destroy(JSC::JSCell* cell)
{
    JSRTCRtpTransceiver* thisObject = static_cast<JSRTCRtpTransceiver*>(cell);
    thisObject->JSRTCRtpTransceiver::~JSRTCRtpTransceiver();
}

JSC_DEFINE_CUSTOM_GETTER(jsRTCRtpTransceiverConstructor, (JSGlobalObject* lexicalGlobalObject, EncodedJSValue thisValue, PropertyName))
{
    SUPPRESS_UNCOUNTED_LOCAL auto& vm = JSC::getVM(lexicalGlobalObject);
    auto throwScope = DECLARE_THROW_SCOPE(vm);
    auto* prototype = jsDynamicCast<JSRTCRtpTransceiverPrototype*>(JSValue::decode(thisValue));
    if (!prototype) [[unlikely]]
        return throwVMTypeError(lexicalGlobalObject, throwScope);
    return JSValue::encode(JSRTCRtpTransceiver::getConstructor(vm, prototype->globalObject()));
}

static inline JSValue jsRTCRtpTransceiver_midGetter(JSGlobalObject& lexicalGlobalObject, JSRTCRtpTransceiver& thisObject)
{
    SUPPRESS_UNCOUNTED_LOCAL auto& vm = JSC::getVM(&lexicalGlobalObject);
    auto throwScope = DECLARE_THROW_SCOPE(vm);
    SUPPRESS_UNCOUNTED_LOCAL auto& impl = thisObject.wrapped();
    RELEASE_AND_RETURN(throwScope, (toJS<IDLNullable<IDLDOMString>>(lexicalGlobalObject, throwScope, impl.mid())));
}

JSC_DEFINE_CUSTOM_GETTER(jsRTCRtpTransceiver_mid, (JSGlobalObject* lexicalGlobalObject, EncodedJSValue thisValue, PropertyName attributeName))
{
    return IDLAttribute<JSRTCRtpTransceiver>::get<jsRTCRtpTransceiver_midGetter, CastedThisErrorBehavior::Assert>(*lexicalGlobalObject, thisValue, attributeName);
}

static inline JSValue jsRTCRtpTransceiver_senderGetter(JSGlobalObject& lexicalGlobalObject, JSRTCRtpTransceiver& thisObject)
{
    SUPPRESS_UNCOUNTED_LOCAL auto& vm = JSC::getVM(&lexicalGlobalObject);
    auto throwScope = DECLARE_THROW_SCOPE(vm);
    SUPPRESS_UNCOUNTED_LOCAL auto& impl = thisObject.wrapped();
    RELEASE_AND_RETURN(throwScope, (toJS<IDLInterface<RTCRtpSender>>(lexicalGlobalObject, *thisObject.globalObject(), throwScope, impl.sender())));
}

JSC_DEFINE_CUSTOM_GETTER(jsRTCRtpTransceiver_sender, (JSGlobalObject* lexicalGlobalObject, EncodedJSValue thisValue, PropertyName attributeName))
{
    return IDLAttribute<JSRTCRtpTransceiver>::get<jsRTCRtpTransceiver_senderGetter, CastedThisErrorBehavior::Assert>(*lexicalGlobalObject, thisValue, attributeName);
}

static inline JSValue jsRTCRtpTransceiver_receiverGetter(JSGlobalObject& lexicalGlobalObject, JSRTCRtpTransceiver& thisObject)
{
    SUPPRESS_UNCOUNTED_LOCAL auto& vm = JSC::getVM(&lexicalGlobalObject);
    auto throwScope = DECLARE_THROW_SCOPE(vm);
    SUPPRESS_UNCOUNTED_LOCAL auto& impl = thisObject.wrapped();
    RELEASE_AND_RETURN(throwScope, (toJS<IDLInterface<RTCRtpReceiver>>(lexicalGlobalObject, *thisObject.globalObject(), throwScope, impl.receiver())));
}

JSC_DEFINE_CUSTOM_GETTER(jsRTCRtpTransceiver_receiver, (JSGlobalObject* lexicalGlobalObject, EncodedJSValue thisValue, PropertyName attributeName))
{
    return IDLAttribute<JSRTCRtpTransceiver>::get<jsRTCRtpTransceiver_receiverGetter, CastedThisErrorBehavior::Assert>(*lexicalGlobalObject, thisValue, attributeName);
}

static inline JSValue jsRTCRtpTransceiver_stoppedGetter(JSGlobalObject& lexicalGlobalObject, JSRTCRtpTransceiver& thisObject)
{
    SUPPRESS_UNCOUNTED_LOCAL auto& vm = JSC::getVM(&lexicalGlobalObject);
    auto throwScope = DECLARE_THROW_SCOPE(vm);
    SUPPRESS_UNCOUNTED_LOCAL auto& impl = thisObject.wrapped();
    RELEASE_AND_RETURN(throwScope, (toJS<IDLBoolean>(lexicalGlobalObject, throwScope, impl.stopped())));
}

JSC_DEFINE_CUSTOM_GETTER(jsRTCRtpTransceiver_stopped, (JSGlobalObject* lexicalGlobalObject, EncodedJSValue thisValue, PropertyName attributeName))
{
    return IDLAttribute<JSRTCRtpTransceiver>::get<jsRTCRtpTransceiver_stoppedGetter, CastedThisErrorBehavior::Assert>(*lexicalGlobalObject, thisValue, attributeName);
}

static inline JSValue jsRTCRtpTransceiver_directionGetter(JSGlobalObject& lexicalGlobalObject, JSRTCRtpTransceiver& thisObject)
{
    SUPPRESS_UNCOUNTED_LOCAL auto& vm = JSC::getVM(&lexicalGlobalObject);
    auto throwScope = DECLARE_THROW_SCOPE(vm);
    SUPPRESS_UNCOUNTED_LOCAL auto& impl = thisObject.wrapped();
    RELEASE_AND_RETURN(throwScope, (toJS<IDLEnumeration<RTCRtpTransceiverDirection>>(lexicalGlobalObject, throwScope, impl.direction())));
}

JSC_DEFINE_CUSTOM_GETTER(jsRTCRtpTransceiver_direction, (JSGlobalObject* lexicalGlobalObject, EncodedJSValue thisValue, PropertyName attributeName))
{
    return IDLAttribute<JSRTCRtpTransceiver>::get<jsRTCRtpTransceiver_directionGetter, CastedThisErrorBehavior::Assert>(*lexicalGlobalObject, thisValue, attributeName);
}

static inline bool setJSRTCRtpTransceiver_directionSetter(JSGlobalObject& lexicalGlobalObject, JSRTCRtpTransceiver& thisObject, JSValue value)
{
    SUPPRESS_UNCOUNTED_LOCAL auto& vm = JSC::getVM(&lexicalGlobalObject);
    UNUSED_PARAM(vm);
    auto throwScope = DECLARE_THROW_SCOPE(vm);
    SUPPRESS_UNCOUNTED_LOCAL auto& impl = thisObject.wrapped();
    auto optionalNativeValue = parseEnumeration<RTCRtpTransceiverDirection>(lexicalGlobalObject, value);
    RETURN_IF_EXCEPTION(throwScope, false);
    if (!optionalNativeValue) [[unlikely]]
        return false;
    invokeFunctorPropagatingExceptionIfNecessary(lexicalGlobalObject, throwScope, [&] {
        return impl.setDirection(optionalNativeValue.value());
    });
    return true;
}

JSC_DEFINE_CUSTOM_SETTER(setJSRTCRtpTransceiver_direction, (JSGlobalObject* lexicalGlobalObject, EncodedJSValue thisValue, EncodedJSValue encodedValue, PropertyName attributeName))
{
    return IDLAttribute<JSRTCRtpTransceiver>::set<setJSRTCRtpTransceiver_directionSetter>(*lexicalGlobalObject, thisValue, encodedValue, attributeName);
}

static inline JSValue jsRTCRtpTransceiver_currentDirectionGetter(JSGlobalObject& lexicalGlobalObject, JSRTCRtpTransceiver& thisObject)
{
    SUPPRESS_UNCOUNTED_LOCAL auto& vm = JSC::getVM(&lexicalGlobalObject);
    auto throwScope = DECLARE_THROW_SCOPE(vm);
    SUPPRESS_UNCOUNTED_LOCAL auto& impl = thisObject.wrapped();
    RELEASE_AND_RETURN(throwScope, (toJS<IDLNullable<IDLEnumeration<RTCRtpTransceiverDirection>>>(lexicalGlobalObject, throwScope, impl.currentDirection())));
}

JSC_DEFINE_CUSTOM_GETTER(jsRTCRtpTransceiver_currentDirection, (JSGlobalObject* lexicalGlobalObject, EncodedJSValue thisValue, PropertyName attributeName))
{
    return IDLAttribute<JSRTCRtpTransceiver>::get<jsRTCRtpTransceiver_currentDirectionGetter, CastedThisErrorBehavior::Assert>(*lexicalGlobalObject, thisValue, attributeName);
}

static inline JSC::EncodedJSValue jsRTCRtpTransceiverPrototypeFunction_stopBody(JSC::JSGlobalObject* lexicalGlobalObject, JSC::CallFrame* callFrame, typename IDLOperation<JSRTCRtpTransceiver>::ClassParameter castedThis)
{
    SUPPRESS_UNCOUNTED_LOCAL auto& vm = JSC::getVM(lexicalGlobalObject);
    auto throwScope = DECLARE_THROW_SCOPE(vm);
    UNUSED_PARAM(throwScope);
    UNUSED_PARAM(callFrame);
    SUPPRESS_UNCOUNTED_LOCAL auto& impl = castedThis->wrapped();
    RELEASE_AND_RETURN(throwScope, JSValue::encode(toJS<IDLUndefined>(*lexicalGlobalObject, throwScope, [&]() -> decltype(auto) { return impl.stop(); })));
}

JSC_DEFINE_HOST_FUNCTION(jsRTCRtpTransceiverPrototypeFunction_stop, (JSGlobalObject* lexicalGlobalObject, CallFrame* callFrame))
{
    return IDLOperation<JSRTCRtpTransceiver>::call<jsRTCRtpTransceiverPrototypeFunction_stopBody>(*lexicalGlobalObject, *callFrame, "stop");
}

static inline JSC::EncodedJSValue jsRTCRtpTransceiverPrototypeFunction_setCodecPreferencesBody(JSC::JSGlobalObject* lexicalGlobalObject, JSC::CallFrame* callFrame, typename IDLOperation<JSRTCRtpTransceiver>::ClassParameter castedThis)
{
    SUPPRESS_UNCOUNTED_LOCAL auto& vm = JSC::getVM(lexicalGlobalObject);
    auto throwScope = DECLARE_THROW_SCOPE(vm);
    UNUSED_PARAM(throwScope);
    UNUSED_PARAM(callFrame);
    SUPPRESS_UNCOUNTED_LOCAL auto& impl = castedThis->wrapped();
    if (callFrame->argumentCount() < 1) [[unlikely]]
        return throwVMError(lexicalGlobalObject, throwScope, createNotEnoughArgumentsError(lexicalGlobalObject));
    EnsureStillAliveScope argument0 = callFrame->uncheckedArgument(0);
    auto codecsConversionResult = convert<IDLSequence<IDLDictionary<RTCRtpCodecCapability>>>(*lexicalGlobalObject, argument0.value());
    if (codecsConversionResult.hasException(throwScope)) [[unlikely]]
       return encodedJSValue();
    RELEASE_AND_RETURN(throwScope, JSValue::encode(toJS<IDLUndefined>(*lexicalGlobalObject, throwScope, [&]() -> decltype(auto) { return impl.setCodecPreferences(codecsConversionResult.releaseReturnValue()); })));
}

JSC_DEFINE_HOST_FUNCTION(jsRTCRtpTransceiverPrototypeFunction_setCodecPreferences, (JSGlobalObject* lexicalGlobalObject, CallFrame* callFrame))
{
    return IDLOperation<JSRTCRtpTransceiver>::call<jsRTCRtpTransceiverPrototypeFunction_setCodecPreferencesBody>(*lexicalGlobalObject, *callFrame, "setCodecPreferences");
}

JSC::GCClient::IsoSubspace* JSRTCRtpTransceiver::subspaceForImpl(JSC::VM& vm)
{
    return WebCore::subspaceForImpl<JSRTCRtpTransceiver, UseCustomHeapCellType::No>(vm, "JSRTCRtpTransceiver"_s,
        [] (auto& spaces) { return spaces.m_clientSubspaceForRTCRtpTransceiver.get(); },
        [] (auto& spaces, auto&& space) { spaces.m_clientSubspaceForRTCRtpTransceiver = std::forward<decltype(space)>(space); },
        [] (auto& spaces) { return spaces.m_subspaceForRTCRtpTransceiver.get(); },
        [] (auto& spaces, auto&& space) { spaces.m_subspaceForRTCRtpTransceiver = std::forward<decltype(space)>(space); }
    );
}

void JSRTCRtpTransceiver::analyzeHeap(JSCell* cell, HeapAnalyzer& analyzer)
{
    auto* thisObject = jsCast<JSRTCRtpTransceiver*>(cell);
    analyzer.setWrappedObjectForCell(cell, &thisObject->wrapped());
    if (RefPtr context = thisObject->scriptExecutionContext())
        analyzer.setLabelForCell(cell, makeString("url "_s, context->url().string()));
    Base::analyzeHeap(cell, analyzer);
}

bool JSRTCRtpTransceiverOwner::isReachableFromOpaqueRoots(JSC::Handle<JSC::Unknown> handle, void*, AbstractSlotVisitor& visitor, ASCIILiteral* reason)
{
    UNUSED_PARAM(handle);
    UNUSED_PARAM(visitor);
    UNUSED_PARAM(reason);
    return false;
}

void JSRTCRtpTransceiverOwner::finalize(JSC::Handle<JSC::Unknown> handle, void* context)
{
    auto* jsRTCRtpTransceiver = static_cast<JSRTCRtpTransceiver*>(handle.slot()->asCell());
    auto& world = *static_cast<DOMWrapperWorld*>(context);
    uncacheWrapper(world, jsRTCRtpTransceiver->protectedWrapped().ptr(), jsRTCRtpTransceiver);
}

WTF_ALLOW_UNSAFE_BUFFER_USAGE_BEGIN
#if ENABLE(BINDING_INTEGRITY)
#if PLATFORM(WIN)
#pragma warning(disable: 4483)
extern "C" { extern void (*const __identifier("??_7RTCRtpTransceiver@WebCore@@6B@")[])(); }
#else
extern "C" { extern void* _ZTVN7WebCore17RTCRtpTransceiverE[]; }
#endif
template<std::same_as<RTCRtpTransceiver> T>
static inline void verifyVTable(RTCRtpTransceiver* ptr) 
{
    if constexpr (std::is_polymorphic_v<T>) {
        const void* actualVTablePointer = getVTablePointer<T>(ptr);
#if PLATFORM(WIN)
        void* expectedVTablePointer = __identifier("??_7RTCRtpTransceiver@WebCore@@6B@");
#else
        void* expectedVTablePointer = &_ZTVN7WebCore17RTCRtpTransceiverE[2];
#endif

        // If you hit this assertion you either have a use after free bug, or
        // RTCRtpTransceiver has subclasses. If RTCRtpTransceiver has subclasses that get passed
        // to toJS() we currently require RTCRtpTransceiver you to opt out of binding hardening
        // by adding the SkipVTableValidation attribute to the interface IDL definition
        RELEASE_ASSERT(actualVTablePointer == expectedVTablePointer);
    }
}
#endif
WTF_ALLOW_UNSAFE_BUFFER_USAGE_END

JSC::JSValue toJSNewlyCreated(JSC::JSGlobalObject*, JSDOMGlobalObject* globalObject, Ref<RTCRtpTransceiver>&& impl)
{
#if ENABLE(BINDING_INTEGRITY)
    verifyVTable<RTCRtpTransceiver>(impl.ptr());
#endif
    return createWrapper<RTCRtpTransceiver>(globalObject, WTFMove(impl));
}

JSC::JSValue toJS(JSC::JSGlobalObject* lexicalGlobalObject, JSDOMGlobalObject* globalObject, RTCRtpTransceiver& impl)
{
    return wrap(lexicalGlobalObject, globalObject, impl);
}

RTCRtpTransceiver* JSRTCRtpTransceiver::toWrapped(JSC::VM&, JSC::JSValue value)
{
    if (auto* wrapper = jsDynamicCast<JSRTCRtpTransceiver*>(value))
        return &wrapper->wrapped();
    return nullptr;
}

}

#endif // ENABLE(WEB_RTC)
