#pragma once

#define MESSAGE_SUBRESOURCELOADER_DIDFINISHLOADING "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 " SubResourceLoader::didFinishLoading"
#define MESSAGE_SUBRESOURCELOADER_WILLSENDREQUESTINTERNAL "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 " SubResourceLoader::willSendRequestInternal: resource load canceled because new request is invalid"
#define MESSAGE_SUBRESOURCELOADER_WILLSENDREQUESTINTERNAL_CANCELLED_INVALID_NEW_REQUEST "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 " SubResourceLoader::willSendRequestInternal: resource load canceled because new request is NULL (1)"
#define MESSAGE_SUBRESOURCELOADER_WILLSENDREQUESTINTERNAL_CANCELLED_TERMINAL_STATE "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 " SubResourceLoader::willSendRequestInternal: resource load canceled because reached terminal state"
#define MESSAGE_SUBRESOURCELOADER_WILLSENDREQUESTINTERNAL_TERMINAL_STATE_CALLING_COMPLETION_HANDLER "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 " SubResourceLoader::willSendRequestInternal: reached terminal state; calling completion handler"
#define MESSAGE_SUBRESOURCELOADER_WILLSENDREQUESTINTERNAL_CANCELLED_INVALID_REQUEST "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 " SubResourceLoader::willSendRequestInternal: resource load canceled because request is NULL (2)"
#define MESSAGE_SUBRESOURCELOADER_WILLSENDREQUESTINTERNAL_RESOURCELOAD_FINISHED "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 " SubResourceLoader::willSendRequestInternal: resource load finished; calling completion handler"
#define MESSAGE_SUBRESOURCELOADER_WILLSENDREQUESTINTERNAL_RESOURCELOAD_CANCELLED_REDIRECT_NOT_ALLOWED "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 " SubResourceLoader::willSendRequestInternal: resource load canceled because not allowed to follow a redirect"
#define MESSAGE_SUBRESOURCELOADER_WILLSENDREQUESTINTERNAL_REACHED_TERMINAL_STATE "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 " SubResourceLoader::willSendRequestInternal: reached terminal state"
#define MESSAGE_SUBRESOURCELOADER_WILLSENDREQUESTINTERNAL_RESOURCE_LOAD_COMPLETED "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 " SubResourceLoader::willSendRequestInternal: resource load completed"
#define MESSAGE_SUBRESOURCELOADER_WILLSENDREQUESTINTERNAL_RESOURCE_LOAD_CANCELLED_TOO_MANY_REDIRECTS "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 " SubResourceLoader::willSendRequestInternal: resource load canceled because too many redirects"
#define MESSAGE_SUBRESOURCELOADER_WILLSENDREQUESTINTERNAL_RESOURCE_LOAD_CANCELLED_CANNOT_REQUEST_AFTER_REDIRECTION "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 " SubResourceLoader::willSendRequestInternal: resource load canceled because CachedResourceLoader::updateRequestAfterRedirection (really CachedResourceLoader::canRequestAfterRedirection) said no"
#define MESSAGE_SUBRESOURCELOADER_WILLSENDREQUESTINTERNAL_RESOURCE_LOAD_CANCELLED_AFTER_USING_BLOCKED_PORT "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 " SubResourceLoader::willSendRequestInternal: resource load (redirect) canceled because it attempted to use a blocked port"
#define MESSAGE_SUBRESOURCELOADER_WILLSENDREQUESTINTERNAL_RESOURCE_LOAD_CANCELLED_AFTER_REDIRECT_DENIED_BY_CORS_POLICY "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 " SubResourceLoader::willSendRequestInternal: resource load canceled because cross-origin redirection denied by CORS policy"
#define MESSAGE_SUBRESOURCELOADER_WILLSENDREQUESTINTERNAL_RESOURCE_LOAD_CANCELLED_AFTER_IMAGE_BEING_DEFERRED "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 " SubResourceLoader::willSendRequestInternal: resource load canceled because it's an image that should be deferred"
#define MESSAGE_SUBRESOURCELOADER_WILLSENDREQUESTINTERNAL_RESOURCE_DONE_NOTIFYING_CLIENTS "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 " SubResourceLoader::willSendRequestInternal: resource done notifying clients"
#define MESSAGE_SUBRESOURCELOADER_DIDRECEIVERESPONSE_CANCELING_LOAD_BLOCKED_BY_CONTENT_POLICY "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 " SubResourceLoader::didReceiveResponse: canceling load because not allowed by content policy"
#define MESSAGE_SUBRESOURCELOADER_DIDRECEIVERESPONSE_CANCELING_LOAD_RECEIVED_UNEXPECTED_RANGE_RESPONSE "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 " SubResourceLoader::didReceiveResponse: canceling load because receiving a range requested response for a non-range request"
#define MESSAGE_SUBRESOURCELOADER_DIDRECEIVERESPONSE_CANCELING_LOAD_BECAUSE_OF_CROSS_ORIGIN_ACCESS_CONTROL "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 " SubResourceLoader::didReceiveResponse: canceling load because of cross origin access control"
#define MESSAGE_SUBRESOURCELOADER_DIDRECEIVERESPONSE_CANCELING_LOAD_BECAUSE_OF_MULTIPART_NON_IMAGE "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 " SubResourceLoader::didReceiveResponse: canceling load because something about a multi-part non-image"
#define MESSAGE_SUBRESOURCELOADER_DIDFINISHLOADING_CANCELED "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 " SubResourceLoader::didFinishLoading: was canceled"
#define MESSAGE_SUBRESOURCELOADER_DIDFINISHLOADING_REACHED_TERMINAL_STATE "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 " SubResourceLoader::didFinishLoading: reached terminal state"
#define MESSAGE_SUBRESOURCELOADER_DIDFINISHLOADING_DID_NOT_REACH_TERMINAL_STATE "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 " SubResourceLoader::didFinishLoading: Did not reach terminal state"
#define MESSAGE_SUBRESOURCELOADER_DIDFAIL "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 " SubResourceLoader::didFail: (type=%d, code=%d)"
#define MESSAGE_SUBRESOURCELOADER_WILLCANCEL "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 " SubResourceLoader::willCancel: (type=%d, code=%d)"
#define MESSAGE_PROGRESSTRACKER_PROGRESSSTARTED "ProgressTracker::progressStarted: frameID %" PRIu64 ", value %f, tracked frames %d, originating frameID %" PRIu64 ", isMainLoad %d"
#define MESSAGE_PROGRESSTRACKER_PROGRESSCOMPLETED "ProgressTracker::progressCompleted: frameID %" PRIu64 ", value %f, tracked frames %d, originating frameID %" PRIu64 ", isMainLoad %d"
#define MESSAGE_PROGRESSTRACKER_FINALPROGRESSCOMPLETE "ProgressTracker::finalProgressComplete: value %f, tracked frames %d, originating frameID %" PRIu64 ", isMainLoad %d, isMainLoadProgressing %d"
#define MESSAGE_FRAMELOADER_SETPROVISIONALDOCUMENTLOADER "[pageID=%" PRIu64 " frameID=%" PRIu64 " isMainFrame=%d] FrameLoader::setProvisionalDocumentLoader: Setting provisional document loader to %" PRIu64 " (was %" PRIu64 ")"
#define MESSAGE_FRAMELOADER_SETSTATE_MAIN_FRAME_LOAD_COMPLETED "[pageID=%" PRIu64 " frameID=%" PRIu64 " isMainFrame=%d] FrameLoader::setState: main frame load completed"
#define MESSAGE_FRAMELOADER_SETPOLICYDOCUMENTLOADER "[pageID=%" PRIu64 " frameID=%" PRIu64 " isMainFrame=%d] FrameLoader::setPolicyDocumentLoader: Setting policy document loader to %" PRIu64 " (was %" PRIu64 ")"
#define MESSAGE_FRAMELOADER_TRANSITIONTOCOMMITTED "[pageID=%" PRIu64 " frameID=%" PRIu64 " isMainFrame=%d] FrameLoader::transitionToCommitted: Clearing provisional document loader (m_provisionalDocumentLoader=%" PRIu64 ")"
#define MESSAGE_FRAMELOADER_SETDOCUMENTLOADER "[pageID=%" PRIu64 " frameID=%" PRIu64 " isMainFrame=%d] FrameLoader::setDocumentLoader: Setting document loader to %" PRIu64 " (was %" PRIu64 ")"
#define MESSAGE_FRAMELOADER_STOPALLLOADERS_CLEARING_PROVISIONAL_DOCUMENT_LOADER "[pageID=%" PRIu64 " frameID=%" PRIu64 " isMainFrame=%d] FrameLoader::stopAllLoaders: Clearing provisional document loader (m_provisionalDocumentLoader=%" PRIu64 ")"
#define MESSAGE_FRAMELOADER_LOADWITHDOCUMENTLOADER_FRAME_LOAD_STARTED "[pageID=%" PRIu64 " frameID=%" PRIu64 " isMainFrame=%d] FrameLoader::loadWithDocumentLoader: frame load started"
#define MESSAGE_FRAMELOADER_LOADWITHDOCUMENTLOADER_MAIN_FRAME_LOAD_STARTED "[pageID=%" PRIu64 " frameID=%" PRIu64 " isMainFrame=%d] FrameLoader::loadWithDocumentLoader: main frame load started"
#define MESSAGE_FRAMELOADER_STOPALLLOADERS "[pageID=%" PRIu64 " frameID=%" PRIu64 " isMainFrame=%d] FrameLoader::stopAllLoaders: m_provisionalDocumentLoader=%" PRIu64 ", m_documentLoader=%" PRIu64 ""
#define MESSAGE_FRAMELOADER_CONTINUELOADAFTERNAVIGATIONPOLICY "[pageID=%" PRIu64 " frameID=%" PRIu64 " isMainFrame=%d] FrameLoader::continueLoadAfterNavigationPolicy: Setting provisional document loader (m_provisionalDocumentLoader=%" PRIu64 ")"
#define MESSAGE_FRAMELOADER_PREPAREFORLOADSTART "[pageID=%" PRIu64 " frameID=%" PRIu64 " isMainFrame=%d] FrameLoader::prepareForLoadStart: Starting frame load"
#define MESSAGE_FRAMELOADER_CHANGELOCATION "[pageID=%" PRIu64 " frameID=%" PRIu64 " isMainFrame=%d] FrameLoader::changeLocation: frame load started"
#define MESSAGE_FRAMELOADER_LOADFRAMEREQUEST_FRAME_LOAD_STARTED "[pageID=%" PRIu64 " frameID=%" PRIu64 " isMainFrame=%d] FrameLoader::loadFrameRequest: frame load started"
#define MESSAGE_FRAMELOADER_CHECKLOADCOMPLETEFORTHISFRAME "[pageID=%" PRIu64 " frameID=%" PRIu64 " isMainFrame=%d] FrameLoader::checkLoadCompleteForThisFrame: Finished frame load"
#define MESSAGE_FRAMELOADER_LOAD_URL "[pageID=%" PRIu64 " frameID=%" PRIu64 " isMainFrame=%d] FrameLoader::loadURL: frame load started"
#define MESSAGE_FRAMELOADER_LOADWITHNAVIGATIONACTION "[pageID=%" PRIu64 " frameID=%" PRIu64 " isMainFrame=%d] FrameLoader::loadWithNavigationAction: frame load started"
#define MESSAGE_FRAMELOADER_LOADURLINTOCHILDFRAME "[pageID=%" PRIu64 " frameID=%" PRIu64 " isMainFrame=%d] FrameLoader::loadURLIntoChildFrame: frame load started"
#define MESSAGE_FRAMELOADER_CONTINUELOADAFTERNAVIGATIONPOLICY_CANNOT_CONTINUE "[pageID=%" PRIu64 " frameID=%" PRIu64 " isMainFrame=%d] FrameLoader::continueLoadAfterNavigationPolicy: can't continue loading frame due to the following reasons (allowNavigationToInvalidURL = %d, requestURLIsValid = %d, navigationPolicyDecision = %d)"
#define MESSAGE_FRAMELOADER_LOAD_FRAMELOADREQUEST "[pageID=%" PRIu64 " frameID=%" PRIu64 " isMainFrame=%d] FrameLoader::load (FrameLoadRequest): frame load started"
#define MESSAGE_FRAMELOADER_LOAD_DOCUMENTLOADER "[pageID=%" PRIu64 " frameID=%" PRIu64 " isMainFrame=%d] FrameLoader::load (DocumentLoader): frame load started"
#define MESSAGE_FRAMELOADER_RELOAD "[pageID=%" PRIu64 " frameID=%" PRIu64 " isMainFrame=%d] FrameLoader::reload: frame load started"
#define MESSAGE_RESOURCELOADER_WILLSENDREQUESTINTERNAL "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", resourceID=%" PRIu64 "] ResourceLoader::willSendRequestInternal: calling completion handler"
#define MESSAGE_DOCUMENTLOADER_STARTLOADINGMAINRESOURCE_EMTPY_DOCUMENT "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", isMainFrame=%d] DocumentLoader::startLoadingMainResource: Returning empty document"
#define MESSAGE_DOCUMENTLOADER_STARTLOADINGMAINRESOURCE_STARTING_LOAD "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", isMainFrame=%d] DocumentLoader::startLoadingMainResource: Starting load"
#define MESSAGE_DOCUMENTLOADER_ATTACHTOFRAME "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", isMainFrame=%d] DocumentLoader::attachToFrame"
#define MESSAGE_DOCUMENTLOADER_DETACHFROMFRAME "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", isMainFrame=%d] DocumentLoader::detachFromFrame"
#define MESSAGE_DOCUMENTLOADER_STOPLOADING "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", isMainFrame=%d] DocumentLoader::stopLoading"
#define MESSAGE_MEDIASESSIONMANAGERCOCOA_SESSIONCANPRODUCEAUDIOCHANGED "MediaSessionManagerCocoa::sessionCanProduceAudioChanged"
#define MESSAGE_MEDIASESSIONMANAGERCOCOA_CLIENTCHARACTERISTICSCHANGED "MediaSessionManagerCocoa::clientCharacteristicsChanged, session ID = %llu"
#define MESSAGE_MEDIASESSIONMANAGERCOCOA_UPDATESESSIONSTATE "MediaSessionManagerCocoa::updateSessionState: AudioCapture(%d), AudioTrack(%d), Video(%d), Audio(%d), VideoAudio(%d), WebAudio(%d)"
#define MESSAGE_PLATFORMMEDIASESSIONMANAGER_REMOVESESSION "PlatformMediaSessionManager::removeSession, session ID = %" PRIu64 ""
#define MESSAGE_PLATFORMMEDIASESSIONMANAGER_SESSIONWILLENDPLAYBACK "PlatformMediaSessionManager::sessionWillEndPlayback, session ID = %" PRIu64 ""
#define MESSAGE_PLATFORMMEDIASESSIONMANAGER_SESSIONCANPRODUCEAUDIOCHANGED "PlatformMediaSessionManager::sessionCanProduceAudioChanged"
#define MESSAGE_PLATFORMMEDIASESSIONMANAGER_ADDSESSION "PlatformMediaSessionManager::addSession, session ID = %" PRIu64 ""
#define MESSAGE_PLATFORMMEDIASESSIONMANAGER_MAYBEACTIVATEAUDIOSESSION_ACTIVE_SESSION_NOT_REQUIRED "PlatformMediaSessionManager::maybeActivateAudioSession:  active audio session not required"
#define MESSAGE_HTMLMEDIAELEMENT_CONSTRUCTOR "HTMLMediaElement::HTMLMediaElement(%" PRIX64 ")"
#define MESSAGE_HTMLMEDIAELEMENT_DESTRUCTOR "HTMLMediaElement::~HTMLMediaElement(%" PRIX64 ")"
#define MESSAGE_HTMLMEDIAELEMENT_SETBUFFERINGPOLICY "HTMLMediaElement::setBufferingPolicy(%" PRIX64 "): %" PRIu8
#define MESSAGE_HTMLMEDIAELEMENT_INSERTEDINTOANCESTOR "HTMLMediaElement::insertedIntoAncestor(%" PRIX64 ")"
#define MESSAGE_HTMLMEDIAELEMENT_REMOVEDFROMANCESTOR "HTMLMediaElement::removedFromAncestor(%" PRIX64 ")"
#define MESSAGE_HTMLMEDIAELEMENT_DIDFINISHINSERTINGNODE "HTMLMediaElement::didFinishInsertingNode(%" PRIX64 ")"
#define MESSAGE_HTMLMEDIAELEMENT_MEDIAPLAYERRATECHANGED "HTMLMediaElement::mediaPlayerRateChanged(%" PRIX64 ") rate: %f"
#define MESSAGE_HTMLMEDIAELEMENT_MEDIAPLAYERTIMECHANGED "HTMLMediaElement::mediaPlayerTimeChanged(%" PRIX64 ")"
#define MESSAGE_HTMLMEDIAELEMENT_SETSHOULDDELAYLOADEVENT "HTMLMediaElement::setShouldDelayLoadEvent(%" PRIX64 ") %" PRIu8
#define MESSAGE_HTMLMEDIAELEMENT_MEDIAPLAYERENGINEUPDATED "HTMLMediaElement::mediaPlayerEngineUpdated(%" PRIX64 ") %s"
#define MESSAGE_HTMLMEDIAELEMENT_CURRENTMEDIATIME_SEEKING "HTMLMediaElement::currentMediaTime(%" PRIX64 ") seeking, returning %f"
#define MESSAGE_HTMLMEDIAELEMENT_UPDATEPLAYSTATE "HTMLMediaElement::updatePlayState(%" PRIX64 ") shouldBePlaying = %d, playerPaused = %d"
#define MESSAGE_HTMLMEDIAELEMENT_VISIBILITYSTATECHANGED "HTMLMediaElement::visibilityStateChanged(%" PRIX64 ") visible = %d"
#define MESSAGE_HTMLMEDIAELEMENT_CREATEMEDIAPLAYER "HTMLMediaElement::createMediaPlayer(%" PRIX64 ")"
#define MESSAGE_HTMLMEDIAELEMENT_PLAY "HTMLMediaElement::play(%" PRIX64 ")"
#define MESSAGE_HTMLMEDIAELEMENT_PLAYINTERNAL "HTMLMediaElement::playInternal(%" PRIX64 ")"
#define MESSAGE_HTMLMEDIAELEMENT_ADDAUDIOTRACK "HTMLMediaElement::addAudioTrack(%" PRIX64 ") id: %s, %s"
#define MESSAGE_HTMLMEDIAELEMENT_ADDVIDEOTRACK "HTMLMediaElement::addVideoTrack(%" PRIX64 ") id: %s, %s"
#define MESSAGE_HTMLMEDIAELEMENT_CANPLAYTYPE "HTMLMediaElement::canPlayType(%" PRIX64 ") %s: %s"
#define MESSAGE_HTMLMEDIAELEMENT_CANTRANSITIONFROMAUTOPLAYTOPLAY "HTMLMediaElement::canTransitionFromAutoplayToPlay(%" PRIX64 ") %s"
#define MESSAGE_HTMLMEDIAELEMENT_CONFIGURETEXTTRACKDISPLAY "HTMLMediaElement::configureTextTrackDisplay(%" PRIX64 ") %s"
#define MESSAGE_HTMLMEDIAELEMENT_CONFIGURETEXTTRACKGROUP "HTMLMediaElement::configureTextTrackGroup(%" PRIX64 ") %s track with language %s and BCP 47 language %s has score %d"
#define MESSAGE_HTMLMEDIAELEMENT_MEDIAENGINEWASUPDATED "HTMLMediaElement::mediaEngineWasUpdated(%" PRIX64 ")"
#define MESSAGE_HTMLMEDIAELEMENT_MEDIAPLAYERCHARACTERISTICSCHANGED "HTMLMediaElement::mediaPlayerCharacteristicChanged(%" PRIX64 ") %s"
#define MESSAGE_HTMLMEDIAELEMENT_MEDIAPLAYERDURATIONCHANGED "HTMLMediaElement::mediaPlayerDurationChanged(%" PRIX64 ") duration = %f, current time = %f"
#define MESSAGE_HTMLMEDIAELEMENT_MEDIAPLAYERSIZECHANGED "HTMLMediaElement::mediaPlayerSizeChanged(%" PRIX64 ") w = %f, h = %f"
#define MESSAGE_HTMLMEDIAELEMENT_PAUSE "HTMLMediaElement::pause(%" PRIX64 ")"
#define MESSAGE_HTMLMEDIAELEMENT_PAUSEINTERNAL "HTMLMediaElement::pauseInternal(%" PRIX64 ")"
#define MESSAGE_HTMLMEDIAELEMENT_PREPAREFORLOAD "HTMLMediaElement::prepareForLoad(%" PRIX64 ") gesture = %d"
#define MESSAGE_HTMLMEDIAELEMENT_REMOVEAUDIOTRACK "HTMLMediaElement::removeAudioTrack(%" PRIX64 ") id: %s, %s"
#define MESSAGE_HTMLMEDIAELEMENT_SCENEIDENTIFIERDIDCHANGE "HTMLMediaElement::sceneIdentifierDidChange(%" PRIX64 ") %s"
#define MESSAGE_HTMLMEDIAELEMENT_SCHEDULECONFIGURETEXTTRACKS_TASK_SCHEDULED "HTMLMediaElement::scheduleConfigureTextTracks(%" PRIX64 ") task scheduled"
#define MESSAGE_HTMLMEDIAELEMENT_SCHEDULECONFIGURETEXTTRACKS_LAMBDA_TASK_FIRED "HTMLMediaElement::scheduleConfigureTextTracks(%" PRIX64 ") lambda(), task fired"
#define MESSAGE_HTMLMEDIAELEMENT_SCHEDULEMEDIAENGINEWASUPDATED_TASK_SCHEDULED "HTMLMediaElement::scheduleMediaEngineWasUpdated(%" PRIX64 ") task scheduled"
#define MESSAGE_HTMLMEDIAELEMENT_SCHEDULEMEDIAENGINEWASUPDATED_LAMBDA_TASK_FIRED "HTMLMediaElement::scheduleMediaEngineWasUpdated(%" PRIX64 ") lambda(), task fired"
#define MESSAGE_HTMLMEDIAELEMENT_SELECTMEDIARESOURCE_LAMBDA_TASK_FIRED "HTMLMediaElement::selectMediaResource(%" PRIX64 ") lambda(), task fired"
#define MESSAGE_HTMLMEDIAELEMENT_SELECTMEDIARESOURCE_NOTHING_TO_LOAD "HTMLMediaElement::selectMediaResource(%" PRIX64 ") nothing to load"
#define MESSAGE_HTMLMEDIAELEMENT_SELECTMEDIARESOURCE_HAS_SRCATTR_PLAYER_NOT_CREATED "HTMLMediaElement::selectMediaResource(%" PRIX64 ") has srcAttr but m_player is not created"
#define MESSAGE_HTMLMEDIAELEMENT_SELECTMEDIARESOURCE_ATTEMPTING_USE_OF_UNATTACHED_MEDIASOURCEHANDLE "HTMLMediaElement::selectMediaResource(%" PRIX64 ") Attempting to use a detached or a previously attached MediaSourceHandle"
#define MESSAGE_HTMLMEDIAELEMENT_SELECTMEDIARESOURCE_USING_SRCOBJECT_PROPERTY "HTMLMediaElement::selectMediaResource(%" PRIX64 ") using 'srcObject' property"
#define MESSAGE_HTMLMEDIAELEMENT_SELECTMEDIARESOURCE_USING_SRC_ATTRIBUTE_URL "HTMLMediaElement::selectMediaResource(%" PRIX64 ") using 'src' attribute url"
#define MESSAGE_HTMLMEDIAELEMENT_SELECTMEDIARESOURCE_EMPTY_SRC "HTMLMediaElement::selectMediaResource(%" PRIX64 ") empty 'src'"
#define MESSAGE_HTMLMEDIAELEMENT_SETAUTOPLAYEVENTPLAYBACKSTATE "HTMLMediaElement::setAutoplayEventPlaybackState(%" PRIX64 ") %s"
#define MESSAGE_HTMLMEDIAELEMENT_SETMUTEDINTERNAL "HTMLMediaElement::setMutedInternal(%" PRIX64 ") %d"
#define MESSAGE_HTMLMEDIAELEMENT_SETNETWORKSTATE "HTMLMediaElement::setNetworkState(%" PRIX64 ") new state = %s, current state = %s"
#define MESSAGE_HTMLMEDIAELEMENT_SETPLAYBACKRATE "HTMLMediaElement::setPlaybackRate(%" PRIX64 ") %f"
#define MESSAGE_HTMLMEDIAELEMENT_SETREADYSTATE "HTMLMediaElement::setReadyState(%" PRIX64 ") new state = %s, current state = %s"
#define MESSAGE_HTMLMEDIAELEMENT_SETSHOWPOSTERFLAG "HTMLMediaElement::setShowPosterFlag(%" PRIX64 ") %d"
#define MESSAGE_HTMLMEDIAELEMENT_SETVOLUME "HTMLMediaElement::setVolume(%" PRIX64 ") %f"
#define MESSAGE_HTMLVIDEOELEMENT_MEDIAPLAYERRENDERINGMODECHANGED "HTMLVideoElement::mediaPlayerRenderingModeChanged(%" PRIX64 ")"
#define MESSAGE_HTMLVIDEOELEMENT_MEDIAPLAYERFIRSTVIDEOFRAMEAVAILABLE "HTMLVideoElement::mediaPlayerFirstVideoFrameAvailable(%" PRIX64 ") m_showPoster = %d"
#define MESSAGE_HTMLVIDEOELEMENT_SCHEDULERESIZEEVENT "HTMLMediaElement::scheduleResizeEvent(%" PRIX64 ") width: %f height: %f"
#define MESSAGE_PERFORMANCELOGGING_MEMORY_USAGE_INFO "Memory usage info dump at %s:"
#define MESSAGE_PERFORMANCELOGGING_MEMORY_USAGE_FOR_KEY "  %s: %llu"
#define MESSAGE_PERFORMANCEMONITOR_MEASURE_POSTLOAD_CPUUSAGE "PerformanceMonitor::measurePostLoadCPUUsage: Process was using %.1f%% CPU after the page load."
#define MESSAGE_PERFORMANCEMONITOR_MEASURE_POSTLOAD_MEMORYUSAGE "PerformanceMonitor::measurePostLoadMemoryUsage: Process was using %" PRIu64 " bytes of memory after the page load."
#define MESSAGE_PERFORMANCEMONITOR_MEASURE_POSTBACKGROUND_MEMORYUSAGE "PerformanceMonitor:measurePostBackgroundingMemoryUsage: Process was using %" PRIu64 " bytes of memory after becoming non visible."
#define MESSAGE_PERFORMANCEMONITOR_MEASURE_POSTBACKGROUND_CPUUSAGE "PerformanceMonitor::measurePostBackgroundingCPUUsage: Process was using %.1f%% CPU after becoming non visible."
#define MESSAGE_PERFORMANCEMONITOR_MEASURE_CPUUSAGE_IN_ACTIVITYSTATE "PerformanceMonitor::measureCPUUsageInActivityState: Process is using %.1f%% CPU in state: %s"
#define MESSAGE_POLICYCHECKIER_CHECKNAVIGATIONPOLICY_CONTINUE_LOAD_IN_ANOTHER_PROCESS "[pageID=%" PRIu64 ", frameID=%" PRIu64 "] PolicyChecker::checkNavigationPolicy: stopping because policyAction from dispatchDecidePolicyForNavigationAction is LoadWillContinueInAnotherProcess"
#define MESSAGE_POLICYCHECKIER_CHECKNAVIGATIONPOLICY_CONTINUE_INITIAL_EMPTY_DOCUMENT "[pageID=%" PRIu64 ", frameID=%" PRIu64 "] PolicyChecker::checkNavigationPolicy: continuing because this is an initial empty document"
#define MESSAGE_LOCALFRAMEVIEW_FIRING_FIRST_VISUALLY_NON_EMPTY_LAYOUT_MILESTONE "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", isMainFrame=%d] LocalFrameView::fireLayoutRelatedMilestonesIfNeeded: Firing first visually non-empty layout milestone on the main frame"
#define MESSAGE_LOCALFRAMEVIEW_FIRING_RESIZE_EVENTS_DISABLED_FOR_PAGE "[pageID=%" PRIu64 ", frameID=%" PRIu64 ", isMainFrame=%d] LocalFrameView::scheduleResizeEventIfNeeded: Not firing resize events because they are temporarily disabled for this page"
#define MESSAGE_LOCALFRAMEVIEW_NOT_PAINTING_LAYOUT_NEEDED "    [pageID=%" PRIu64 ", frameID=%" PRIu64 ", isMainFrame=%d] LocalFrameView::paintContents: Not painting because render tree needs layout"
#define MESSAGE_SERVICEWORKERTHREADPROXY_REMOVEFETCH "ServiceWorkerThreadProxy::removeFetch %llu"
#define MESSAGE_FONTCACHECORETEXT_REGISTER_FONT "Registering font %{private}s with fontURL %{private}s"
#define MESSAGE_FONTCACHECORETEXT_REGISTER_ERROR "Could not register font %{private}s, error %s"
#define MESSAGE_WEBCORE_TEST_LOG "WebCore log message for testing (%u)"
