partial interface WorkerGlobalScope {
    [EnabledBySetting=ShapeDetection, SecureContext] attribute BarcodeDetectorConstructor BarcodeDetector;
    [EnabledBySetting=ShapeDetection, SecureContext] attribute FaceDetectorConstructor FaceDetector;
    [EnabledBySetting=ShapeDetection, SecureContext] attribute TextDetectorConstructor TextDetector;
    [EnabledBySetting=WebGPUEnabled, SecureContext] attribute GPUConstructor GPU;
    [EnabledBySetting=WebGPUEnabled, SecureContext] attribute GPUAdapterConstructor GPUAdapter;
    [EnabledBySetting=WebGPUEnabled, SecureContext] attribute GPUAdapterInfoConstructor GPUAdapterInfo;
    [EnabledBySetting=WebGPUEnabled, SecureContext] attribute GPUBindGroupConstructor GPUBindGroup;
    [EnabledBySetting=WebGPUEnabled, SecureContext] attribute GPUBindGroupLayoutConstructor GPUBindGroupLayout;
    [SecureContext] attribute GPUBufferConstructor GPUBuffer;
    [SecureContext] attribute GPUBufferUsageConstructor GPUBufferUsage;
    [SecureContext] attribute GPUColorWriteConstructor GPUColorWrite;
    [EnabledBySetting=WebGPUEnabled, SecureContext] attribute GPUCommandBufferConstructor GPUCommandBuffer;
    [SecureContext] attribute GPUCommandEncoderConstructor GPUCommandEncoder;
    [EnabledBySetting=WebGPUEnabled, SecureContext] attribute GPUCompilationInfoConstructor GPUCompilationInfo;
    [EnabledBySetting=WebGPUEnabled, SecureContext] attribute GPUCompilationMessageConstructor GPUCompilationMessage;
    [SecureContext] attribute GPUComputePassEncoderConstructor GPUComputePassEncoder;
    [EnabledBySetting=WebGPUEnabled, SecureContext] attribute GPUComputePipelineConstructor GPUComputePipeline;
    [EnabledBySetting=WebGPUEnabled, SecureContext] attribute GPUDeviceConstructor GPUDevice;
    [EnabledBySetting=WebGPUEnabled, SecureContext] attribute GPUDeviceLostInfoConstructor GPUDeviceLostInfo;
    [EnabledBySetting=WebGPUEnabled, SecureContext] attribute GPUExternalTextureConstructor GPUExternalTexture;
    [EnabledBySetting=WebGPUEnabled, SecureContext] attribute GPUInternalErrorConstructor GPUInternalError;
    [SecureContext] attribute GPUMapModeConstructor GPUMapMode;
    [EnabledBySetting=WebGPUEnabled, SecureContext] attribute GPUOutOfMemoryErrorConstructor GPUOutOfMemoryError;
    [EnabledBySetting=WebGPUEnabled, SecureContext] attribute GPUPipelineLayoutConstructor GPUPipelineLayout;
    [EnabledBySetting=WebGPUEnabled, SecureContext] attribute GPUQuerySetConstructor GPUQuerySet;
    [SecureContext] attribute GPUQueueConstructor GPUQueue;
    [EnabledBySetting=WebGPUEnabled, SecureContext] attribute GPURenderBundleConstructor GPURenderBundle;
    [EnabledBySetting=WebGPUEnabled, SecureContext] attribute GPURenderBundleEncoderConstructor GPURenderBundleEncoder;
    [SecureContext] attribute GPURenderPassEncoderConstructor GPURenderPassEncoder;
    [EnabledBySetting=WebGPUEnabled, SecureContext] attribute GPURenderPipelineConstructor GPURenderPipeline;
    [EnabledBySetting=WebGPUEnabled, SecureContext] attribute GPUSamplerConstructor GPUSampler;
    [EnabledBySetting=WebGPUEnabled, SecureContext] attribute GPUShaderModuleConstructor GPUShaderModule;
    [SecureContext] attribute GPUShaderStageConstructor GPUShaderStage;
    [EnabledBySetting=WebGPUEnabled, SecureContext] attribute GPUSupportedFeaturesConstructor GPUSupportedFeatures;
    [EnabledBySetting=WebGPUEnabled, SecureContext] attribute GPUSupportedLimitsConstructor GPUSupportedLimits;
    [EnabledBySetting=WebGPUEnabled, SecureContext] attribute GPUTextureConstructor GPUTexture;
    [SecureContext] attribute GPUTextureUsageConstructor GPUTextureUsage;
    [EnabledBySetting=WebGPUEnabled, SecureContext] attribute GPUTextureViewConstructor GPUTextureView;
    [EnabledBySetting=WebGPUEnabled, SecureContext] attribute GPUUncapturedErrorEventConstructor GPUUncapturedErrorEvent;
    [EnabledBySetting=WebGPUEnabled, SecureContext] attribute GPUValidationErrorConstructor GPUValidationError;
    [EnabledBySetting=WebGPUEnabled, SecureContext] attribute WGSLLanguageFeaturesConstructor WGSLLanguageFeatures;
    [EnabledBySetting=CacheAPIEnabled, SecureContext] attribute DOMCacheConstructor Cache;
    [EnabledBySetting=CacheAPIEnabled, SecureContext] attribute DOMCacheStorageConstructor CacheStorage;
    attribute FetchHeadersConstructor Headers;
    attribute FetchRequestConstructor Request;
    attribute FetchResponseConstructor Response;
    [EnabledBySetting=FileSystemEnabled, SecureContext] attribute FileSystemDirectoryHandleConstructor FileSystemDirectoryHandle;
    [EnabledBySetting=FileSystemEnabled, SecureContext] attribute FileSystemFileHandleConstructor FileSystemFileHandle;
    [EnabledBySetting=FileSystemEnabled, SecureContext] attribute FileSystemHandleConstructor FileSystemHandle;
    [EnabledBySetting=FileSystemWritableStreamEnabled, SecureContext] attribute FileSystemWritableFileStreamConstructor FileSystemWritableFileStream;
    [EnabledBySetting=IndexedDBAPIEnabled] attribute IDBCursorConstructor IDBCursor;
    [EnabledBySetting=IndexedDBAPIEnabled] attribute IDBCursorWithValueConstructor IDBCursorWithValue;
    [EnabledBySetting=IndexedDBAPIEnabled] attribute IDBDatabaseConstructor IDBDatabase;
    [EnabledBySetting=IndexedDBAPIEnabled] attribute IDBFactoryConstructor IDBFactory;
    [EnabledBySetting=IndexedDBAPIEnabled] attribute IDBIndexConstructor IDBIndex;
    [EnabledBySetting=IndexedDBAPIEnabled] attribute IDBKeyRangeConstructor IDBKeyRange;
    [EnabledBySetting=IndexedDBAPIEnabled] attribute IDBObjectStoreConstructor IDBObjectStore;
    [EnabledBySetting=IndexedDBAPIEnabled] attribute IDBOpenDBRequestConstructor IDBOpenDBRequest;
    [EnabledBySetting=IndexedDBAPIEnabled] attribute IDBRequestConstructor IDBRequest;
    [EnabledBySetting=IndexedDBAPIEnabled] attribute IDBTransactionConstructor IDBTransaction;
    [EnabledBySetting=IndexedDBAPIEnabled] attribute IDBVersionChangeEventConstructor IDBVersionChangeEvent;
    [Conditional=WEB_RTC, EnabledBySetting=PeerConnectionEnabled] attribute RTCDataChannelConstructor RTCDataChannel;
    [Conditional=WEB_RTC, EnabledBySetting=WebRTCEncodedTransformEnabled] attribute RTCTransformEventConstructor RTCTransformEvent;
    [EnabledBySetting=PermissionsAPIEnabled] attribute PermissionsConstructor Permissions;
    [EnabledBySetting=PushAPIEnabled, SecureContext] attribute PushManagerConstructor PushManager;
    [EnabledBySetting=PushAPIEnabled, SecureContext] attribute PushSubscriptionConstructor PushSubscription;
    [EnabledBySetting=PushAPIEnabled, SecureContext] attribute PushSubscriptionOptionsConstructor PushSubscriptionOptions;
    [EnabledBySetting=DeprecationReportingEnabled] attribute DeprecationReportBodyConstructor DeprecationReportBody;
    attribute ReportConstructor Report;
    attribute ReportBodyConstructor ReportBody;
    attribute ReportingObserverConstructor ReportingObserver;
    [EnabledBySetting=StorageAPIEnabled, SecureContext] attribute StorageManagerConstructor StorageManager;
    [EnabledBySetting=URLPatternAPIEnabled] attribute URLPatternConstructor URLPattern;
    [EnabledBySetting=WebLocksAPIEnabled, SecureContext] attribute WebLockConstructor Lock;
    [EnabledBySetting=WebLocksAPIEnabled, SecureContext] attribute WebLockManagerConstructor LockManager;
    [Conditional=VIDEO] attribute VideoColorSpaceConstructor VideoColorSpace;
    attribute CloseEventConstructor CloseEvent;
    [EnabledBySetting=WebSocketEnabled] attribute WebSocketConstructor WebSocket;
    [EnabledBySetting=WebTransportEnabled, SecureContext] attribute WebTransportConstructor WebTransport;
    [EnabledBySetting=WebTransportEnabled, SecureContext] attribute WebTransportBidirectionalStreamConstructor WebTransportBidirectionalStream;
    [EnabledBySetting=WebTransportEnabled, SecureContext] attribute WebTransportDatagramDuplexStreamConstructor WebTransportDatagramDuplexStream;
    [EnabledBySetting=WebTransportEnabled, SecureContext] attribute WebTransportErrorConstructor WebTransportError;
    [EnabledBySetting=WebTransportEnabled, SecureContext] attribute WebTransportReceiveStreamConstructor WebTransportReceiveStream;
    [EnabledBySetting=WebTransportEnabled, SecureContext] attribute WebTransportSendStreamConstructor WebTransportSendStream;
    [SecureContext] attribute CryptoKeyConstructor CryptoKey;
    [SecureContext] attribute SubtleCryptoConstructor SubtleCrypto;
    attribute DOMMatrixConstructor DOMMatrix;
    attribute DOMMatrixReadOnlyConstructor DOMMatrixReadOnly;
    attribute FontFaceConstructor FontFace;
    attribute FontFaceSetConstructor FontFaceSet;
    attribute CSSKeywordValueConstructor CSSKeywordValue;
    attribute CSSNumericValueConstructor CSSNumericValue;
    attribute CSSOMVariableReferenceValueConstructor CSSVariableReferenceValue;
    attribute CSSStyleImageValueConstructor CSSImageValue;
    attribute CSSStyleValueConstructor CSSStyleValue;
    attribute CSSUnitValueConstructor CSSUnitValue;
    attribute CSSUnparsedValueConstructor CSSUnparsedValue;
    attribute StylePropertyMapReadOnlyConstructor StylePropertyMapReadOnly;
    [EnabledBySetting=CSSTypedOMColorEnabled] attribute CSSHSLConstructor CSSHSL;
    [EnabledBySetting=CSSTypedOMColorEnabled] attribute CSSHWBConstructor CSSHWB;
    [EnabledBySetting=CSSTypedOMColorEnabled] attribute CSSLCHConstructor CSSLCH;
    [EnabledBySetting=CSSTypedOMColorEnabled] attribute CSSLabConstructor CSSLab;
    [EnabledBySetting=CSSTypedOMColorEnabled] attribute CSSOKLCHConstructor CSSOKLCH;
    [EnabledBySetting=CSSTypedOMColorEnabled] attribute CSSOKLabConstructor CSSOKLab;
    [EnabledBySetting=CSSTypedOMColorEnabled] attribute CSSOMColorConstructor CSSColor;
    [EnabledBySetting=CSSTypedOMColorEnabled] attribute CSSOMColorValueConstructor CSSColorValue;
    [EnabledBySetting=CSSTypedOMColorEnabled] attribute CSSRGBConstructor CSSRGB;
    attribute CSSMathClampConstructor CSSMathClamp;
    attribute CSSMathInvertConstructor CSSMathInvert;
    attribute CSSMathMaxConstructor CSSMathMax;
    attribute CSSMathMinConstructor CSSMathMin;
    attribute CSSMathNegateConstructor CSSMathNegate;
    attribute CSSMathProductConstructor CSSMathProduct;
    attribute CSSMathSumConstructor CSSMathSum;
    attribute CSSMathValueConstructor CSSMathValue;
    attribute CSSNumericArrayConstructor CSSNumericArray;
    attribute CSSMatrixComponentConstructor CSSMatrixComponent;
    attribute CSSPerspectiveConstructor CSSPerspective;
    attribute CSSRotateConstructor CSSRotate;
    attribute CSSScaleConstructor CSSScale;
    attribute CSSSkewConstructor CSSSkew;
    attribute CSSSkewXConstructor CSSSkewX;
    attribute CSSSkewYConstructor CSSSkewY;
    attribute CSSTransformComponentConstructor CSSTransformComponent;
    attribute CSSTransformValueConstructor CSSTransformValue;
    attribute CSSTranslateConstructor CSSTranslate;
    [EnabledBySetting=BroadcastChannelEnabled] attribute BroadcastChannelConstructor BroadcastChannel;
    attribute DOMExceptionConstructor DOMException;
    attribute DOMPointConstructor DOMPoint;
    attribute DOMPointReadOnlyConstructor DOMPointReadOnly;
    attribute DOMQuadConstructor DOMQuad;
    attribute DOMRectConstructor DOMRect;
    attribute DOMRectReadOnlyConstructor DOMRectReadOnly;
    attribute DOMStringListConstructor DOMStringList;
    attribute MessageChannelConstructor MessageChannel;
    attribute MessageEventConstructor MessageEvent;
    attribute MessagePortConstructor MessagePort;
    [EnabledBySetting=ObservableEnabled] attribute ObservableConstructor Observable;
    attribute ProgressEventConstructor ProgressEvent;
    attribute SecurityPolicyViolationEventConstructor SecurityPolicyViolationEvent;
    [EnabledBySetting=ObservableEnabled] attribute SubscriberConstructor Subscriber;
    [PrivateIdentifier] attribute TextDecoderStreamDecoderConstructor TextDecoderStreamDecoder;
    [PrivateIdentifier] attribute TextEncoderStreamEncoderConstructor TextEncoderStreamEncoder;
    [EnabledBySetting=TrustedTypesEnabled] attribute TrustedHTMLConstructor TrustedHTML;
    [EnabledBySetting=TrustedTypesEnabled] attribute TrustedScriptConstructor TrustedScript;
    [EnabledBySetting=TrustedTypesEnabled] attribute TrustedScriptURLConstructor TrustedScriptURL;
    [EnabledBySetting=TrustedTypesEnabled] attribute TrustedTypePolicyConstructor TrustedTypePolicy;
    [EnabledBySetting=TrustedTypesEnabled] attribute TrustedTypePolicyFactoryConstructor TrustedTypePolicyFactory;
    attribute BlobConstructor Blob;
    attribute FileConstructor File;
    attribute FileListConstructor FileList;
    [EnabledBySetting=FileReaderAPIEnabled] attribute FileReaderConstructor FileReader;
    attribute DOMFormDataConstructor FormData;
    attribute ImageBitmapConstructor ImageBitmap;
    attribute ImageDataConstructor ImageData;
    [Conditional=OFFSCREEN_CANVAS&OFFSCREEN_CANVAS_IN_WORKERS, EnabledBySetting=OffscreenCanvasEnabled, EnabledForContext] attribute OffscreenCanvasConstructor OffscreenCanvas;
    attribute TextMetricsConstructor TextMetrics;
    attribute CanvasGradientConstructor CanvasGradient;
    attribute CanvasPatternConstructor CanvasPattern;
    [EnabledBySetting=WebGPUEnabled, SecureContext] attribute GPUCanvasContextConstructor GPUCanvasContext;
    attribute ImageBitmapRenderingContextConstructor ImageBitmapRenderingContext;
    [Conditional=OFFSCREEN_CANVAS&OFFSCREEN_CANVAS_IN_WORKERS, EnabledBySetting=OffscreenCanvasEnabled, EnabledForContext] attribute OffscreenCanvasRenderingContext2DConstructor OffscreenCanvasRenderingContext2D;
    attribute Path2DConstructor Path2D;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGL2RenderingContextConstructor WebGL2RenderingContext;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLActiveInfoConstructor WebGLActiveInfo;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLBufferConstructor WebGLBuffer;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLContextEventConstructor WebGLContextEvent;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLFramebufferConstructor WebGLFramebuffer;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLProgramConstructor WebGLProgram;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLQueryConstructor WebGLQuery;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLRenderbufferConstructor WebGLRenderbuffer;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLRenderingContextConstructor WebGLRenderingContext;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLSamplerConstructor WebGLSampler;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLShaderConstructor WebGLShader;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLShaderPrecisionFormatConstructor WebGLShaderPrecisionFormat;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLSyncConstructor WebGLSync;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLTextureConstructor WebGLTexture;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLTransformFeedbackConstructor WebGLTransformFeedback;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLUniformLocationConstructor WebGLUniformLocation;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLVertexArrayObjectConstructor WebGLVertexArrayObject;
    [Conditional=VIDEO] attribute AudioTrackConfigurationConstructor AudioTrackConfiguration;
    [Conditional=VIDEO] attribute VideoTrackConfigurationConstructor VideoTrackConfiguration;
    attribute CryptoConstructor Crypto;
    attribute EventSourceConstructor EventSource;
    [EnabledBySetting=NavigatorUserAgentDataJavaScriptAPIEnabled] attribute NavigatorUADataConstructor NavigatorUAData;
    attribute WorkerNavigatorConstructor WorkerNavigator;
    attribute WorkerGlobalScopeConstructor WorkerGlobalScope;
    attribute WorkerLocationConstructor WorkerLocation;
    [EnabledBySetting=ServiceWorkerNavigationPreloadEnabled] attribute NavigationPreloadManagerConstructor NavigationPreloadManager;
    [EnabledBySetting=ServiceWorkersEnabled, SecureContext] attribute ServiceWorkerConstructor ServiceWorker;
    [EnabledBySetting=ServiceWorkersEnabled, SecureContext] attribute ServiceWorkerContainerConstructor ServiceWorkerContainer;
    [EnabledBySetting=ServiceWorkersEnabled, SecureContext] attribute ServiceWorkerRegistrationConstructor ServiceWorkerRegistration;
    [EnabledBySetting=ServiceWorkersEnabled&BackgroundFetchAPIEnabled] attribute BackgroundFetchManagerConstructor BackgroundFetchManager;
    [EnabledBySetting=ServiceWorkersEnabled&BackgroundFetchAPIEnabled] attribute BackgroundFetchRecordConstructor BackgroundFetchRecord;
    [EnabledBySetting=ServiceWorkersEnabled&BackgroundFetchAPIEnabled] attribute BackgroundFetchRegistrationConstructor BackgroundFetchRegistration;
    [EnabledBySetting=ServiceWorkersEnabled&BackgroundFetchAPIEnabled] attribute BackgroundFetchUpdateUIEventConstructor BackgroundFetchUpdateUIEvent;
    attribute XMLHttpRequestEventTargetConstructor XMLHttpRequestEventTarget;
    attribute XMLHttpRequestUploadConstructor XMLHttpRequestUpload;
};
